### ISSUE TITLE
[External links]: Add documentation for external links

### ISSUE THREAD

**Issue by maya** [uswds/uswds#1322]
## Issue type
- UI component
## Description

We added external links in #1253, but did not add documentation to go along with it. 

It might be a good idea to add some reasoning or usability instructions for it.

cc: @jpyuda @bradnunnally @ericadeahl

**Comment by bradnunnally** [comment]
@maya, @kategarklavs and I discussed and this content is going to be included in the broader effort to add "context of use" content to all the components that are on the site. I'm going to close this comment for now. 

Thanks for the push on getting content like this out.

**Comment by maya** [comment]
Re-opening this as this work did not get done. Adding from Erica re: the external link icons https://github.com/18F/web-design-standards/pull/1253#issuecomment-226345030:
>I'm still not totally convinced this is the best practice for external links, and I've been reviewing some conflicting advice, so I'd like to mark this component for further review.

**Comment by joshbruce** [comment]
I concur with the assessment of the "slight weirdness for visited links" made in the related merge. Three images could be used (inverse, normal, and visited). Alternatively, Font Awesome has a unicode character that might be worth trying to add via `::after` - because it's an actual glyph it will adopt the `color` attribute - otherwise, any text-based color changes will run into similar issues.

We might also consider putting it in a `sup` position. This would allow an annotation look; thereby, making a consistent style choice between footnote references (a al Wikipedia https://en.wikipedia.org/wiki/Middle_Ages) and external site notification. I also remember seeing an icon (might have been in Stack) that was less obtrusive compared to the Font Awesome image.

Sorry if this is way off topic, just saw an opening and took it. ;)

**Comment by thisisdano** [comment]
How might our consider our guidance on external links given the findings from gov.uk that discovered the external link icon technique wasn't useful or effective?

https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/
https://github.com/alphagov/govuk_frontend_toolkit/pull/293
