### ISSUE TITLE
[Refactor HTML/CSS] Refactor footer component

### ISSUE THREAD

**Issue by juliaelman** [uswds/uswds#1431]
Remove extra specificity, and complex class names in footer, break up some parts into separate files.

Refs https://github.com/18F/web-design-standards/issues/1342

**Comment by msecret** [comment]
Some notes:
- Each footer link uses a grid class (like 1/6) to position itself. What if this was more dynamic, so a user wouldn't have to figure out what grid class to use but could just add as many links as required.
- Possible ways to split up:
  - Footer sections, like `footer-primary`, `footer-secondary`
  - Horizontal navigation component for links
  - Horizontal block navigation (for nav of big footer)
  - Logo component
  - Sign-up block isn't specific to footer.
- contact links class just aligns right
- social links class just removes text decoration from links (could maybe be done in a nav class)
- Should the social links really be background images? seems like it makes them less extendable because you have to add a new class to add a new one, rather then just adding HTML link and image.

**Comment by el-mapache** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
