### ISSUE TITLE
Incorrect role is used for the Close button

### ISSUE THREAD

**Issue by davidstenger** [uswds/uswds#1656]
**Issue**:
In responsive view, the Role attribute has not been specified for the Close button. 
See attachment [ButtonRole_ResponsiveViewl_ExtendedHeader.png](https://drive.google.com/open?id=0ByQeU_iOqP_iNFJ6S1JPY2JWZzg)

**Solution**:
Update the Close button to have an accessible name, role, state, and value. 
Refer to: http://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html?cm_mc_uid=79615163929714381992345&cm_mc_sid_50200000=1449171451 for more details.

**Comment by toolness** [comment]
Hmm, this might have changed since this bug was filed. As far as I can tell, right now the close button consists of a `<button>` that wraps an `<img alt="close">`, which means that it has a role of button, a value of "close", and a state of ... unpressed, I think?  In any case, it seems to work fine with NVDA, though on some browsers it says "graphic close" instead of just "close" which could be confusing. Probably fixable by putting `aria-label="close"` on the wrapping `<button>` element...

**Comment by toolness** [comment]
@nickbristow would you mind taking a look at this one?  As far as I can tell, we're currently using a valid role/state/value for the close button, but we could use a second opinion...

**Comment by maya** [comment]
ANDI, the accessiblity tool, shows the accessible name of "close" for the button, so it seems to be OK:
<img width="778" alt="screen shot 2018-02-12 at 3 43 32 pm" src="https://user-images.githubusercontent.com/5249443/36126075-bfce27b8-100b-11e8-9d04-557dc571311d.png">

@nickbristow can you take a look and let us know?

**Comment by maya** [comment]
Closing this as it's programmatically determined.
