### ISSUE TITLE
[Grid]: Remove usa-width-one-whole column

### ISSUE THREAD

**Issue by maya** [uswds/uswds#1973]
Is there a use for this column? People should just add content directly in `usa-grid` for full-width content. I've seen this misused a few times on various repos.

**Comment by toolness** [comment]
I've been running an [analysis of how various sites use the Standards](https://gist.github.com/toolness/5810d08414fc3d941e00bf296a7dc928), and according to it, around 31% of sites that seem to use the Standards are using `usa-width-one-whole`, which is a lot (in fact, the only column widths that are more popular appear to be one-half, one-third, and two-thirds).  So if we do get rid of this, we should be sure to communicate it very broadly, since a lot of folks appear to be using it.

@maya do you have examples of improper use of this class?  If we have e.g. a CSS selector that can be used to detect improper use, then I can write a script that finds all improper uses of it across USWDS sites...

**Comment by maya** [comment]
@toolness That is high. It's possible that the [jekyll template](https://github.com/18F/uswds-jekyll/blob/master/_layouts/landing.html#L26) has something to do with it as well, as it's propagating it out to everyone who uses it. Are you looking at html files in that search?

**Comment by maya** [comment]
Note: if this is removed, it won't have an adverse effect bc it doesn't do anything. It would be basically an extra div. The only use case I could imagine for this may be if we found a way to use multiple rows inside `usa-grid`. From the last I remembered, the system only works with one row per grid container. @msecret might remember as well / have thoughts.

**Comment by msecret** [comment]
Yea it's not supposed to work nested, but I think you technically can hack it a bit to make it work. It could potentially keep some consistency in code, especially if the code is componentized like React, or templated. For instance, lets say I have a react `grid` component where I can pass how many columns I want. I should be able to pass one column. If this class didn't exist, then the structure of the code would change from being something like:

```
<div class="usa-grid">
  <div class="usa-column-one">
  ...
</div>
```

to:

```
<div class="usa-grid">
  ...
</div>
```

That ^ changes the structure of the HTML, which could be confusing and cause other things to break. So it might make sense to have the one column grid just for consistency like that.

**Comment by vinhboy** [comment]
Hrmm... Is it really true this does nothing? Because I use it all over my code. I just kind of assumed it's the semantically correctly name because of the other ones.

I think this page in general is just confusing: https://standards.usa.gov/components/grids/

Under `Grid Examples` It should have the semantic names of the columns instead of dummy text. Also, it should not show `1/1` if it doesn't exists...

**Comment by msecret** [comment]
It does exist as a class, and that class does have CSS applied to it. Here is some of the CSS rules for the `.usa-width-one-whole` class:

```css
margin-right: 0;
float: left;
display: block;
width: 100%;
```

Because it's 100% width, 0 margin and floated left, it's not practically doing anything. But it's totally fine to keep in your code because it's not doing anything bad.

**Comment by maya** [comment]
The current grid will be deprecated in version 2.0, see https://v2.designsystem.digital.gov/utilities/layout-grid/
