### ISSUE TITLE
Accordion Header Focus Issue on Firefox OSX

### ISSUE THREAD

**Issue by linzhaoken** [uswds/uswds#2111]
## Description
When click the Accordion header, it is not get focused, so if I click tab key, it won't give me expected focus. It works ok on Safari and Chrome.

My OS Version: macOS Sierra version 10.12.5
FireFox Version: 52.2.1

## Steps to reproduce the issue

1. Click one of Accordion header
2. Click tab key
3. keep eye on the next focus element.

This will also affect click enter key to expand and close Accordion.

Expected results: the next Accordion will be focused.
The Results I got: the next Accordion is not focused.

**Comment by toolness** [comment]
Hmm, so this is an interesting problem that I'm not sure what to do about.

According to [Firefox bug 756028](https://bugzilla.mozilla.org/show_bug.cgi?id=756028):

> ... we try to implement the focus behaviour of the native operating system as best we can. Which means that on Mac, buttons are not focused when clicked

This isn't the whole story, though. As @linzhaoken mentioned, this problem doesn't occur on Safari, even though Safari doesn't focus the button when the user clicks on it.  It *does* update the "current tab index" when the user clicks on it, though, which is why expected behavior occurs when <kbd>Tab</kbd> is pressed. The same is not the case with Firefox, however. I've just filed [Firefox bug 1391428](https://bugzilla.mozilla.org/show_bug.cgi?id=1391428) to address this.

However, until this bug is fixed on Firefox's end, I'm not sure what we should do.  One alternative might be to forcibly focus the button when it's clicked; this would fix our immediate concern, and it would effectively make button-clicking work like Chrome's does on all platforms (Chrome ignores the "button clicks do not focus the buttons" convention on OS X).  We could even do user agent detection for Firefox, to ensure that Safari's behavior stays the same. My only concern about this approach, really, is that it's not very easy to unit test.

**Comment by maya** [comment]
Closing this as it's a Firefox behavior and not something the USWDS team can resolve. Thank you for opening the issue in Firefox's Bugzilla and we'll track any progress from there.
