### ISSUE TITLE
Button changes, no documentation

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#2171]
It appears in 1.4 there were some significant changes to the buttons and I cannot find any reference. It appears usa-button-outline became usa-button-secondary, and usa-button-secondary became usa-button-red. I am not a fan of the change as it moves away from the standardized color naming, but I need to know if this is going to be permanent so that I can make the appropriate updates in several projects.

**Comment by joshbruce** [comment]
I actually appreciate the change with primary and secondary (was already using them that way. The specific change I appreciate is the separation between intent (function) and straight color (see `variables`).

Though I am considering a button class in my extension:

- `usa-button-destructive`
- (and possibly, though not likely) `usa-button-destructive-outline`

Then the style and naming make sense from a UX perspective. 

- Primary action.
- Secondary action.
- Destructive action.

Could translate to:

- Save.
- Cancel.
- Delete.

Respectively.

Didn’t even know about `usa-button-red` - thanks for that.

**Comment by evetsreklaw** [comment]
I am of the school that CSS is about styling and not about user interaction. This way you simplify and minimize they styling you need (write once use in several places). Since I am not building it myself, I just need to know what the road ahead will be so I can make the necessary changes. In my opinion, moving from 1.3 to 1.4 should not be breaking basic styling and certainly not without documentation.

**Comment by joshbruce** [comment]
That's fair. Think I come from the school that colors should be named colors. :)

Given the changes to the `variables.scss` separating the functional names from the color names - and having the functional names reference the color names I wouldn't be surprised if 2.0 saw the functional color name become deprecated entirely; thereby, having the palette be divided between primary, secondary (and possibly tertiary).

**Comment by evetsreklaw** [comment]
I guess it would have helped if I looked at variables.scss in detail. I think it answers my question about the road ahead. I am definitely not opposed to colors being named colors. I agree with your assessment for 2.0.

**Comment by maya** [comment]
Thanks for bringing this to our attention. I could see how this could be confusing without any documentation. We'll take a look at this issue and get back to you.

**Comment by evetsreklaw** [comment]
I just went through my code and made the updates. I would like to make a recommendation that the terms "primary" and "secondary" should only relate to hierarchy and never be related to color. The button-primary and button secondary are not logical names (IMO). Since default and primary are the same, do away with primary and just use usa-button and usa-button-inverse. Secondary-inverse should just be use-button-black-outlined.

**Comment by maya** [comment]
From @thisisdano in #2237:

>The button color variants available at https://components.standards.usa.gov/components/detail/buttons--red.html aren't documented on our site. Users don't know these variants exist, which is a particularly acute issue since we changed the styling of usa-button-secondary to outline from red. These variants are important. They are often necessary to communicate functionality, and if they don't appear on our site they may as well not exist.
>
>todo
> - Document all available button variants on standards.usa.gov

**Comment by maya** [comment]
Hello again, we've returned to the previous naming convention in #2767 and show them all on the site: https://v2.designsystem.digital.gov/components/buttons/

This ensures they are more consistent with the themed variables these buttons use. Thanks again!
