### ISSUE TITLE
[Fractal] Code not formatted when aXe extension enabled in Chrome

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2273]
The code glitches from formatted to un-formatted. It's very hard to read in it's un-formatted state:

## This is what I see
![](http://g.recordit.co/TQKAjv0ri3.gif)

## This is what I expect
<img width="1209" alt="screen shot 2017-12-14 at 4 17 26 pm" src="https://user-images.githubusercontent.com/5249443/34020694-867544b0-e0ea-11e7-84c9-efca5fa7f05e.png">

**Comment by donjo** [comment]
Are you seeing this locally? I'm able to replicate the problem on components.standards.usa.gov but not on my local install of the `develop` branch.

**Comment by maya** [comment]
This is only on components.standards.usa.gov, works locally for me too.

**Comment by donjo** [comment]
Hmm I started to see it locally too but at unpredictable intervals. I noticed I couldn't replicate it in any other browsers so I figured there may be a browser extension causing problems. I uninstalled the aXe extension and it seems like the problem is gone. Did you have that installed? And if so, when you uninstall it does the problem go away?

**Comment by maya** [comment]
Yeah same, goes away when I disable aXe extension.

**Comment by maya** [comment]
This seems to be fixed, https://github.com/frctl/fractal/issues/397.
