### ISSUE TITLE
aXe tests running on visual regression tests

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2355]
I noticed that aXe tests are running for each component with the command `node spec/visual-regression-tester.js test --updateGolden`:

```
"grid"
  on small-desktop (412x732)
    ✓ has no aXe violations (74ms)
    ✓ is the new golden screenshot (1040ms)
  on large-desktop (1280x732)
    ✓ has no aXe violations (60ms)
    ✓ is the new golden screenshot (1106ms)
```

It would speed up the time to just have the screenshots run. Is this possible @toolness?

**Comment by maya** [comment]
hey @toolness, any insight on this?

**Comment by toolness** [comment]
Oh, hmm...  I'm not sure if there's an easy way to disable the aXe tests currently, though they ran so quickly that I didn't mind them running.  The `visual-regression-tester.js` script does have a `-g/--grep` flag that allows you to only run tests matching a certain pattern (e.g. `large-desktop`) but it doesn't currently provide a way to _skip_ tests matching a certain pattern, which might be useful for skipping the `aXe` tests. 

The test runner is also just calling [`mocha`](https://mochajs.org/) under-the-hood, but it looks like mocha doesn't support skipping certain tests based on a regex.

I guess the closest thing that can be done is to define an environment variable that tells the runner whether to skip the aXe tests or not, and then check that environment variable when defining the aXe tests.

Is there a particular reason you want to skip them?  Just to make the tests run faster, or something else?

**Comment by maya** [comment]
Yes, to make the tests run faster.

**Comment by el-mapache** [comment]
Ive been thinking about this a bit, and disabling the aXe tests when generating the golden master doesn't seem like the correct thing to do. We want the tests to run because a 'master' reference file that contains HTML which doesn't pass accessibility requirements should be considered an invalid reference.

Although the tests are not super speedy to run, we generate these files fairly irregularly and I think we'd be better served trying to increase the speed of our slowest tests, rather than cutting them completely.

**Comment by maya** [comment]
Sounds good to me, we can close this.
