### ISSUE TITLE
Add ability to pull in component code into an app

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2395]
While I was notifying folks to update the banner text (#2093), I heard from one person that they'd like a central place to access the code so if it changes, it would automatically get pulled in.

>Is there a way we can simply pull in the ​latest approved code at runtime rather than having to update our app when USWDS changes its mind?
>
>We use angularJS. The problem is that we now have to update our app. I would rather have the developers access this content from a URL shared by USDS so that no code change was ever necessary.

Although the government banner content likely will not change much in the future, how might we enable something like this?

**Comment by hursey013** [comment]
Yeah I had this same thought - we could offer the text of this banner in json format and host it somewhere so that folks cant import that. If they happen to be using Jekyll they could use something like https://github.com/18F/jekyll-get to pull in the same json file too. Lastly, again for the Jekyll crowd, if they happen to be using the `uswds-jekyll` theme, they would get that update automatically when they updated the theme version.

Are there any other aspect of the site besides that banner that would need this functionality?

**Comment by maya** [comment]
The govt banner is the only thing that I can think of for now. In the future, if we ever provide a Privacy page or other policy pages that govt sites are required to have, it could be different. Also, there was some discussion around maintenance here: https://github.com/uswds/uswds/issues/1738.

**Comment by hursey013** [comment]
It sort of sounds like from https://github.com/uswds/uswds/issues/1738 that it's an open issue whether or not to include that detail text at all, which I would tend to agree with. Are you aware of any further decisions to that end?

**Comment by maya** [comment]
There was no decision to remove it and don't think it should be. It serves a real user need that was informed by solid research. Whether the USWDS or another group ends up being the gatekeeper of the text is another thing, but if it's not the USWDS, I don't know who would be the one to do this. This doesn't mean we can't have a blank banner component, too, that would be great to have.
