### ISSUE TITLE
Update spacing utilities naming convention to something that's easy to use and recall

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2431]
Based on a poll in our public slack channel and internal front-end channel, it's (nearly) unanimous that people prefer **t-shirt sizes** (`margin-top-sm`, `margin-top-md`, `margin-top-lg`) for spacing over a **numeric scale** (`margin-top-1`, `margin-top-2`, `margin-top-3`) and **named scale** (`margin-top-half`, `margin-top-double`, `margin-top-triple`).

## Current votes
- **Numeric scale**: 2
- **T-shirt sizes**: 17
- **Named scale**: 0

I recommend we use the geometric progression outlined here: https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62

**Comment by thisisdano** [comment]
I admit this ongoing discussion is wearing me down. And I don't take my continued pushback against this proposal lightly — I am aware of the trends in our findings and in the larger design system community. Still, we are working to develop a system that works with flexibility and precision across a broad range of projects and use cases. Continued practical use points me in the direction of a static named system, neither t-shirt size nor numeric, and pushes me against these findings.

My experience building responsive websites points me to the following 13 useful units of whitespace for sites of all kinds. Not all sites use all these steps, but it's not unusual for a project to use all of them or most of them — particularly as the functionality of a project gets more complex. The boldfaced units are certainly the _most_ critical, but every step on this scale has its use.

pixel     | grid 8  | t-shirt | relative  | named     |
---       | ---     | ---     | ---       | ---       |
**1px**   | 1px     | 1px     | 1px       | pixel
**2px**   | 2px     | xxs     | smallest  | eighth
**4px**   | 05      | xs      | smaller   | quarter
**8px**   | 1       | sm      | small     | half
12px      | 105     | —       | —         | half-plus
**16px**  | 2       | md      | base      | base
24px      | 3       | —       | —         | base-plus
**32px**  | 4       | lg      | large     | double
40px      | 5       | —       | —         | double-plus
**48px**  | 6       | xl      | larger    | triple
56px      | 7       | —       | —         | triple-plus
**64px**  | 8       | xxl     | largest   | quad
72px      | 9       | —       | —         | quad-plus

Whatever the solution, I want it to work consistently and universally, and leave near-zero instances where designers and developers need to choose values outside the system to achieve the needed result. In general, I find the subset allowed with something like t-shirt to be too narrow. And I feel strongly that the 13 values listed above cover 95%+ of spacing needs, even for demanding applications.

_As an aside, for now, I will also say that I prefer relative sizing (base, smaller|tighter|lighter) to t-shirt (sm, md, lg)  for reasons of conceptual consistency, and alignment with established naming conventions._

I worry that a theme-defined spacing scale will make it more difficult to provide reliable modular components. This isn't a deal-breaker, in all cases, necessarily. To me, evaluating the balance comes down to the real experiential differences between elements in the palette, and the difference in scale between the system palette and the project theme palette.

Specifically, I am more inclined to adopt a relative, settings-based theme palette when a) the experiential difference between steps in the scale is relatively modest (an example might be `border-radius`); and b) there are many more elements in the system palette than are practical in any specific project (an example might be `color`).

In the instance of spacing scale, I will argue that the experiential difference between steps is _not_ modest and that there isn't significant difference between the size of the system spacing scale and a proposed theme scale. In face, I propose that the 13 steps outlined above should be the system palette for spacing scale (with the addition of responsive breakpoint values).

The complete system spacing scale would look like the following 22 sizes, with proportional sizing at standard margin and padding sizes, and "physical" sizing at responsive sizes (all based on an 8px grid):

pixel  |  name
--- | --- 
`1px` | pixel
`2px` | eighth
`4px` | quarter
`8px` | half
`12px` | half-plus
`16px` | base
`24px` | base-plus
`32px` | double
`40px` | double-plus
`48px` | triple
`56px` | triple-plus
`64px` | quad
`72px` | quad-plus


pixel  |  name
--- | --- 
`160px` | card
`240px` | card-plus
`320px` | mobile
`480px` | mobile-plus
`640px` | tablet
`880px` | tablet-plus
`1024px` | desktop
`1200px` | desktop-plus
`1400px` | widescreen 

This could result in a statement like the following in component SASS, which is both readable and descriptive:

```
@include at-media(desktop){
  @include min-height(card-plus);
}
```

This spacing scale naming system is both discrete and relatively unambiguous. Most spacing scales use abstraction to try and simplify the system. This post is not an argument against abstraction — it's useful and has a place when the the values are subject to change and the specific values are less important than the metaphor established by the abstraction. I argue that for spacing, the values can and perhaps _should_ be immutable (for reasons of predictability and modularity) and that the specific value is more meaningful than the metaphor.

For me, media queries are a good example of the value over of the specific over the more abstract metaphor. While I'm all too aware that there is no canonical definition of `mobile` or `tablet` and that ymmv across the spectrum of devices and scales, there is absolutely no kind of definition (by design!) about what `sm`, `md`, or `lg` means. Thus, as a designer or a developer, from project to project (and very frequently within a single project) there's a real need to cross-reference just what `md` means _in this instance_. There's a necessary translation layer between the `md` in the code and the `tablet` in the mind. Why not just go and use `tablet` in the full understanding that they are both technically abstractions, but one has some practical intrinsic value?

In practice, this has been tremendously useful. Not only do I not find myself comparing and cross-referencing far less — but I have some reasonable expectation that responsive components I build will respond similarly in projects that use the same responsive naming and value. This has real importance for project-to-project modularity and predictability in a system like USWDS where we expect our components to behave predictably in diverse environments.

In my experience, the benefits of t-shirt for spacing scale (familiarity, "simplicity", and concision) do not compare to the practical benefits outlined above. T-shirt cannot reasonably accommodate what I consider the necessary breadth of a consistent, practical "universal" spacing system — and it introduces unnecessary unpredictability and ambiguity for a stylistic element (spacing) whose effect is so powerful and critical to effective, sophisticated design work.

**Comment by stphnwlkr** [comment]
So with all the discussion about which naming convention, especially with all the variations, why not just use the value? No ambiguity with margin-top-32 or padding-left-20 or layout-1440.

**Comment by thisisdano** [comment]
@stphnwlkr I agree that that solution has a certain appeal, though I have found — by trying this out in  practice — that using specific numbers is too difficult to remember. That solution provides a high degree of specificity and control, but (certainly in my experience) at the expense of usability. 

I tend to look for solutions that allow you to remember a pattern or a system of naming instead of remembering specific magic numbers.

**Comment by stphnwlkr** [comment]
@thisisdano Thanks for the response. I find that the ambiguity of xl or larger or, God forbid, triple-plus for spacing would send me back to the source code to figure out what those values actually are. For me, the grid 8 would be my next choice because it is just math.  The numeric values are easier for me to visualize as I am working.

**Comment by thisisdano** [comment]
I think at some point you have to let the absolute values go. This is a necessary abstraction.

**Comment by stphnwlkr** [comment]
Not trying to beat a dead horse, but replacing "30" with "triple"  or "35" with "triple-plus" is the opposite of abstraction. You are now hiding simplicity with complexity. Especially if you change your base to 16, then you have to remember that triple-plus now means 56, where 35 always equals 35.  The only place where it makes some sense is negative spacing, but I am not sure if that should drive the entire convention. I really like the way 2.0 is headed and I will learn the system when it is published -  just voicing an opinion.

**Comment by thisisdano** [comment]
I could be comfortable using a spacing unit multiplier system like the following, based on a base spacing unit of `8px`:

| name | value |
|---|---|
| `1px` | 1px |
| `2px` | 2px |
| `05` | 0.5 spacing units
| `1` | 1 spacing unit
| `105` | 1.5 spacing units
| `2` | 2 spacing units
| `3` | 3 spacing units
| `4` | 4 spacing units
| `5` | 5 spacing units
| `6` | 6 spacing units
| `7` | 7 spacing units
| `8` | 8 spacing units
| `9` | 9 spacing units

Plus `-neg` prefixed values (like `-neg-1px` or `-neg-2`) for negative spacing units.

What I'm looking for is something that can accommodate what I consider the necessary spacing units, something that is simple to remember and apply, and something that doesn't introduce critical ambiguities, and something that is both consistent with the rest of the system and works to strengthen the system as a whole.

I think there are some ambiguities between the use of numerals here and in our layout grid system, but I feel OK that these ambiguities aren't too serious.

**Comment by maya** [comment]
I think the system above could work well bc it's simpler, much easier to recall numbers, and easier to remember the system, especially as you're prototyping and need to adjust spacing on the fly.

In our current (old) grid system, we heard a couple people having problems with remembering how to spell certain ratios (`one-twelfth`, `five-twelfths`, `-twelvths`?) See "The naming convention is confusing" in #2137 and I think the previous spacing recommendation would have some similiar recall issues.

**Comment by thisisdano** [comment]
@stphnwlkr we are moving in that direction for layout grid. 
See https://github.com/uswds/uswds/pull/2422

**Comment by nrakochy** [comment]
You might also check out the conventions used by [Bulma](https://bulma.io/documentation/columns/sizes), which are rather nice and might offer some ideas for naming conventions. 

I think key insight there is that any `column` in a `columns` section will auto-size based on the total number present, and specific naming/classes is only added to the column(s) that need it  - 

```

**Comment by maya** [comment]
This is done and using a numeric scale as seen here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-utility-docs/utilities/spacing/
