### ISSUE TITLE
Add basic colors to utilities

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2432]
Add basic colors to utilities so that folks can prototype more easily.

Add ROYGBP + cyan colors to basic utilities.

### Text
`usa-red-lightest`
`usa-red-lighter`
`usa-red-light`
`usa-red`
`usa-red-dark`
`usa-red-darker`
`usa-red-darkest`

### Background
`usa-bg-red-lightest`
`usa-bg-red-lighter`
`usa-bg-red-light`
`usa-bg-red`
`usa-bg-red-dark`
`usa-bg-red-darker`
`usa-bg-red-darkest`

Could potentially scale back from 7 to 5 variants.

**Comment by stphnwlkr** [comment]
Please keep seven variations.

**Comment by maya** [comment]
Noted, thanks @stphnwlkr!

**Comment by thisisdano** [comment]
OK, so there are a few issues here I want to unpack and challenge, but first I'll say that I agree in principle that there is some limited subset of colors that would be useful in basic prototyping and should be available in the default set.

But I don't think this is how we should do it.

I believe there is real system utility in using the default mechanics of the system to promote system literacy and I worry that this proposal unintentionally undermines system literacy.

- - -

Stepping back, let's look at the utility class system, the color system palette, and the project theme palette.

These proposed utilities deviate from the standard utility class naming in a way that may or may not be simpler, but is inconsistent with the broader system and would introduce misleading expectations. Whatever default colors we add to utilities should use the `u-color-[NAME]` and `u-background-color-[NAME]` construction that the rest of the utilities use.

As for the colors themselves, the system color palette has no `purple` color family. Colors that might traditionally fall under the purple hue are shared between `indigo` and `violet`. Might `violet` be named `purple` instead? Perhaps, but I like that the current system is aligned with ROYGBIV+ and that indigo and violet disambiguate purple. That said, I could be open to renaming `violet` as `purple` but I do not consider it an improvement from the point of view of consistency.

I don't like that this subset excludes so many color families. I understand that exclusion is the nature of a subset, but I feel that the default "basic palette" (let's call it) could be more representative of the system palette. I would prefer to see more families and fewer grades in the basic palette.

In fact, this basic palette, as proposed, becomes a third palette system, a hybrid of the existing palettes:

| palette | color families | grades
| --- |--- |--- 
| **System palette** | hue-based | numeric/fixed
| **Project theme palette** | use-based | relative
| **Proposed basic palette** | hue-based | relative

This introduces another mental model into the system and continues to obscure the grades we use to assure Section 508 conformance.

I want whatever system of prototyping and sketching in code to support understanding our system color palette and the method by which you might build a theme palette. The process has pedagogic value. This proposed basic palette is like a _shadow_ system palette that obscures and possibly supplants both the system palette and the project theme palette. It feels like a counterproposal to the existing palettes instead of something that works with them.

My guidance for sketching with code, prototyping, and working with color goes something like this:

1. **To start, work only in grayscale.** Consider color progressive enhancement. Instead, work with type, hierarchy, and grade to sketch and build your first iteration. The system could support this by developing a "sketching palette" that includes (in part) a grade-only set of utilities used for the equivalent of a pencil sketch — like `u-color-5` — in grades 0-5 and 10-100. This helps understand the grades that would eventually be necessary in the final project system palette, and test for Section 508 color contrast with the "magic number" grade test.
2. **Next, experiment with color families.** Use simple color testing to try to map a color family onto the hues determined in the pencil sketch. The system could support this with a component of the sketching palette that was hue-only, taking a representative hue from each color family as a single value passed to the utility — like `u-color-red-warm`.
3. **Refine using plugins.** This gives you enough information to adjust your utility settings with plugins, adding the full color families you've identified as promising. Setting plugins like `$plugin-color-red-warm` to the `$global-color-plugins` list var in `_project-utilities-settings.scss`would apply those values to any utility that accepts color. Then adjust to suit project needs.
4. **Apply final values to project theme palette settings.** At this point, you have all the information you need to build or modify a project theme palette — the palette every USWDS project should use as their standard production palette.

Sketching and prototyping is important to me, and it's an important feature of USWDS 2.0. I want to work to support it and provide a usable, practical, and pedagogically consistent pathway from idea to production code.

I believe in both the concrete specificity of utility units and the scalable abstraction of production naming systems. I want to build a bridge between them in the  prototyping → production workflow. I think there are strong pedagogic and practical accessibility benefits to understanding the color grade system, and to encouraging the use of color as progressive enhancement, secondary to other elements of form, shape, and hierarchy. I realize that the workflow and solution I propose doesn't provide as much utility out of the box, but I believe that the _process and progression_ I outline above — from simple to more complex — is important to assuring solid accessible design, understanding the range, intention, and capabilities of the design system, and assuring a better final product for everyone who uses our websites. This is what I want to encourage and build into our tools.

**Comment by maya** [comment]
Done, colors here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-utility-docs/utilities/color/
