### ISSUE TITLE
Reasoning for adding new fonts: United Sans and Roboto Mono

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2434]
@hursey013 mentioned being curious as to why we are adding two new fonts to the USWDS: United Sans and Roboto Mono. See: https://github.com/uswds/uswds/pull/2287#pullrequestreview-108698213

@thisisdano replied:
>Hasn't been covered yet, but I consider this a topic for upcoming guidance. But also even in the absence of guidance, by starting to build a library of font definitions, we can begin to use the system's new ability to normalize font sizes — and be more simpler and more programmatic about building our @font-face rules

Let's discuss the reasoning for adding each additional font and see if each of them really is necessary. 

- Reasons for adding United Sans font
  - Is Source Sans Pro not sufficient?
- Reasons for adding new Roboto Mono font
  - Is the current mono font stack not sufficient (`Consolas, Monaco, "Andale Mono", monospace`)? Seems like one mono stack font would be enough.

- Does it make sense for us to provide this in core or something people can customize outside of the USWDS?
- Do we intend to add more fonts than these two (e.g. another serif)?

**Comment by thisisdano** [comment]
One of the goal sets of USWDS 2.0 is to make the entire system more flexible, modular, and resilient, while maintaining some measure of system coherence. I think that building more font choice into the system, and providing a pathway to supporting new project typefaces, is in the service of this goal.

If we're asking whether adding and supporting new faces is because the existing faces are not sufficient, I think the answer is a clear yes — if only because we've seen how often sites using USWDS have implemented some custom solution with non-default faces. From my perspective, when there's a pattern of users implementing designs that necessitate a non-system solution we have to look at the system solutions and determine if this is an instance where we should change the system to accommodate the user need signaled with this behavior or classify this behavior as one we work to actively discourage.

In this instance, I think we should work to change the system. I don't believe that guidance tailored to a single set of faces is sufficient. I think our system and our guidance should acknowledge that typeface choice is an area where there is occasionally a legitimate need to use non-default solutions.

What I'm proposing should, to some degree, be considered distinct from default guidance. Adding this-or-that face into the system is distinct from actively promoting that face as the best solution for most users. I think _that_ debate is one we will have, but one for later.

To me, this issue is about modularity, resilience, and flexibility — what happens when you choose a face outside the boundary of the system, how to integrate that new typeface into the system, and how to integrate new components and solutions developed with that typeface back into the system.

A common problem with changing typeface is that every typeface is different. Obvious, yes, but the difference between typefaces goes beyond the way a face looks. There is very little consistency from face to face around how large a face appears on screen — how big it looks to a reader (optical size) and how much space the face actually occupies (metrics).

If we want our system to be more modular and resilient, we should work to create a system that still performs well, regardless of the chosen typeface — and whether or not that specific font actually loads on the user's machine. If the font doesn't load, the layout definitely shouldn't break, and, even better, it should be deformed as little as possible.

And we want the guidance we give to work as well as possible, regardless of the typeface. If we say that font size `f8` is a good size for screen reading on a desktop monitor, we want this to be as true as possible from face to face. I don't think it's reasonable to assure that things work 100% seamlessly, but we want to be doing out best to make it as seamless as possible. And it isn't seamless when we swap a typeface like Source Sans Pro for a one like Merriweather, when they differ in metric size by about 6%.

This impacts the effectiveness of a page layout. The work that visual designers do to calibrate the perceptual hierarchy and readability of a page is absolutely affected by a 6% change.

I think it's important that we work to create a system where our guidance is reliable, and where teams can make appropriate typeface decisions without needing to consider whether their chosen face will break our components. Adding new faces into the system and providing a method by which those faces can be used consistently and well in the system is an important way to demonstrate that we're working toward a practical solution.

**Comment by maya** [comment]
This is some good reasoning that we can probably refer back to and possibly incorporate into docs. Closing as this has been addressed.
