### ISSUE TITLE
Max-width sizing not accurate

### ISSUE THREAD

**Issue by hursey013** [uswds/uswds#2440]
On `release-2.0` the out of the box sizing seems to be off. Using `u-max-width-desktop` results in an  element which is `64rem` or `640px` wide. I would expect the default desktop size to be significantly larger.

**Comment by thisisdano** [comment]
I _think_ I have this fixed in another branch — the new value should be ~1024px. But let me check, maybe the rem calculations are off...

**Comment by thisisdano** [comment]
So, I think what's up with this is that the rem calculation is dependent on the `$theme-root-font-size` variable in `_settings.scss`. This var is set to 16px by default. 

This differs from the current USWDS root of `10px`. To prevent any unintentional ill effects, the existing USWDS is still tied to `10px` but all the utilities are defined by the `$theme-root-font-size` var.

As we get closer to integration, we'll rebuild our existing components with new tools and vars to access a common root font size value (and do all the rem calcs automatically, instead of with a hardcode). When we do this, it will allow any user to install USWDS on any system, regardless of a pre-existing root font size.

USWDS would probably want to declare `html { font-size: $theme-root-font-size; }` or whatever as well, but I think our path is clear when we integrate utilities and components.

For now, though, change the value of `$theme-root-font-size` in your project settings and you should get the expected 1024px calc (`102.4rem`).

We can also just change the default to 10px! It shouldn't make any effect on the look and feel of the output (as long as the root is actually set to 10px in the markup).

**Comment by thisisdano** [comment]
Update: I've tested this, and yes, it works as outlined above.
