### ISSUE TITLE
Investigate automating parts of our release process

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2613]
We'd like to try to take around 30 mins for our [release process](https://github.com/uswds/uswds/wiki/Release-process#publishing-a-new-release), but have historically gone over.

@el-mapache mentioned we may be able to automate parts of this process and we should take a look at what we can do.

**Comment by el-mapache** [comment]
I've looked into this and I don't think the benefits are worth writing scripts to automate our releases.

To wit:

* Releases are more onerous because we are releasing both a prerelease and a release branch regularly. Once beta is out we heretically won't be pushing many, if any, changes to the 1.x branch.

* We can't actually automate the publishing process to npm, since all updates require an `otp` code. Although npm does expose an `otp` flag, the person kicking off the publish task would still need to generate that code and supply it; and the release process would have to complete before the token expires.

* Having to remember/lookup multiple commands to handle versioning and publishing is more or less the same as the two commands we have to run now.
