### ISSUE TITLE
[Header]: Close expanded dropdown navigation when user clicks away

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2617]
via @mariamarrero in #1905
>Once the menu is opened, it does not close unless a user clicks on the tab. Have you considered changing it so that when a user clicks somewhere on the page (for example in the search box), the menu closes without the click, but also keeping the option of closing it when the user clicks on the tab?
>
>PS: We have gotten direct comments from users on these 2 issues.

**Comment by el-mapache** [comment]
@maya @thisisdano Update! So I have some code that more or less does what we want it to do. However, since the mega menu behavior is controlled by the accordion JS, we are getting some unintended side effects.

I should be able to clear those up, but I think a better solution is to make a new `dropdown` JS component to handle this kind of behavior. Then the menu can use that.

Since that would be a breaking change, we'd want to put it with the 2.0 release. I'd like to know if this is something we actually want to push out with the first version, or if we should de-prioritize it for now. I'm totally cool with either. It shouldn't really be too much work to make a new component!

Alternatively, we can also keep both versions of the menu, and deprecate and remove the accordion based one at a later date.

**Comment by maya** [comment]
@el-mapache Nice! Either solution sounds good to me. I don't think we need to prioritize this, but you can feel free to pick up if you don't have other things to work on.

**Comment by maya** [comment]
Fixed in #2669. Will go into the 2.0 release.
