### ISSUE TITLE
Allow setting hero image in settings

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3093]
Currently, the hero image is a background image that needs to be overridden as custom CSS. It could be a lot simpler if developers could set this image in project settings!

**Comment by stphnwlkr** [comment]
This would be great. I planned on submitting this a couple of weeks ago and got distracted (look at the butterfly). This would serve as a default because developers would still need to use custom css on pages that use a different hero image. I removed the image line completely from my scss and know it has to be done manually. I was also using a bit of script to randomly change the image.
