### ISSUE TITLE
v2.2.1: path refactor results in 'hero.png' not found

### ISSUE THREAD

**Issue by kkoskelin** [uswds/uswds#3116]
## Description

When attempting to upgrade from our currently locked "2.1.0" to "^2.2.1", parcel reports it cannot find 'hero.png' within my project's non-existent `web-client/img` folder.
```
🚨  /(redacted)/web-client/img/hero.png: ENOENT: no such file or directory, open '/(redacted)/web-client/img/hero.png'
Error: ENOENT: no such file or directory, open '/(redacted)/web-client/img/hero.png'
```

Reference is found in some recently refactored paths:
```
src/stylesheets/settings/_settings-components.scss:$theme-hero-image:  '../img/hero.png' !default;
src/stylesheets/theme/_uswds-theme-components.scss:$theme-hero-image: '../img/hero.png';
```

**Comment by thisisdano** [comment]
The new `$theme-hero-image` setting introduced in `2.2.0` can be used to point the hero image to any valid image, relative to the location of the compiled USWDS stylesheet. Its default is `'../img/hero.png'`.

Specifically, it's used in the `usa-hero` styles like so:

### v2.2.0+
```
.usa-hero {
  background-image: url('#{$theme-hero-image}');
}
``` 

### < v2.2.0
```
.usa-hero {
  background-image: url('#{$theme-image-path}/hero.png');
}
``` 

Since this image is probably not an image included in the `uswds` distribution assets, it may be set to any valid path and now does not reference the `$theme-image-path` setting (which is intended to be used as the relative path to the USWDS assets; default: `'../img'`).

If your current build is failing, look at the `$theme-hero-image` setting in `_uswds-theme-components.scss`. Do you need to update it to match the location of your desired hero image?

There's a bit more documentation in the release notes: https://github.com/uswds/uswds/releases/tag/v2.2.0

Can you check your project settings and let me know if adjusting the value of `$theme-hero-image` fixes your problem?

**Comment by kkoskelin** [comment]
Thanks for the reference, I'll check it out.
