### ISSUE TITLE
Source Sans Pro Regular is not included in uswds-2.2.1

### ISSUE THREAD

**Issue by sharms** [uswds/uswds#3122]
## Source Sans Pro Regular is not included in uswds-2.2.1
Downloading uswds-2.2.1.zip from https://designsystem.digital.gov/download/ does not include the font Source Sans Pro Regular, however this is needed by the default configuration.

## Description
The font exists in src but does not appear to make it to the archive file: https://github.com/uswds/uswds/blob/develop/src/fonts/source-sans-pro/sourcesanspro-regular-webfont.woff

By default this is used in scss: https://github.com/uswds/uswds/blob/7707bff386c98b051243e75218db6a09dc660168/src/stylesheets/core/_system-tokens.scss#L279

**Comment by thisisdano** [comment]
Also missing:
- sourcesanspro-semibolditalic-webfont.woff2
- sourcesanspro-lightitalic-webfont.ttf
- sourcesanspro-lightitalic-webfont.woff
- sourcesanspro-lightitalic-webfont.woff2
- sourcesanspro-regular-webfont.ttf
- sourcesanspro-regular-webfont.woff
- sourcesanspro-regular-webfont.woff2
- sourcesanspro-semibold-webfont.ttf
- sourcesanspro-semibold-webfont.woff
- sourcesanspro-semibold-webfont.woff2
- sourcesanspro-semibolditalic-webfont.ttf
- sourcesanspro-semibolditalic-webfont.woff

Looks like there's some issue with creating the zip archive in the release script. I've regenerated the `.zip` files and updated the release. It actually took a two passes of running the script to make it output properly, so that's another issue we'll need to investigate.

@sharms can you try again and confirm that it's working for you now?

**Comment by sharms** [comment]
Its back thanks!
