### ISSUE TITLE
Radio input nested in a <label> tag doesn't style correctly.

### ISSUE THREAD

**Issue by stevenbuccini** [uswds/uswds#3136]
## Description

Using the `for` attribute in the `<label>` tag:

![](https://user-images.githubusercontent.com/2475615/63402563-b754b680-c390-11e9-9e17-632f29dbc533.png)

Using an `<input>` nested in a `<label>`:

![](https://user-images.githubusercontent.com/2475615/63402580-c6d3ff80-c390-11e9-82fe-cc55698fdc33.png)

This also breaks in the for= implementation if the <label> tags are placed above the input. Interestingly enough, only the top input is rendered incorrectly while the bottom one renders correctly. I have not tested cases where N > 2

## Steps to reproduce the issue
1. Create a static webpage with the DOM seen in the screenshots above
2. Load in a browser

**Comment by mejiaj** [comment]
@stevenbuccini 

I just get the default input styles when trying the following markup:

![image](https://user-images.githubusercontent.com/3385219/70353521-2caaa100-1833-11ea-84bd-4ca453ebc4a3.png)
```html
<input type="radio" name="business-report" id="business-report-yes" value="true" required="required">
<label for="business-report-yes">Yes</label>
<input type="radio" name="business-report" id="business-report-no" value="false" required="required">
<label for="business-report-no">No</label>
```

Which makes sense because the structure isn't like the [docs](https://designsystem.digital.gov/components/form-controls/#radio-buttons).

```html
<div class="usa-radio">
  <input class="usa-radio__input" id="stanton" type="radio" checked name="historical-figures-2" value="stanton">
  <label class="usa-radio__label" for="stanton">Elizabeth Cady Stanton</label>
</div>
```

Are you using this in a CMS like Drupal alongside the USWDS drupal theme?

I didn't notice any issues with using `for` either.

**Comment by thisisdano** [comment]
This may be a `v1`-only issue

**Comment by thisisdano** [comment]
Since this appears to be in the 1.x branch, we won't be fixing it — 1.x is in maintenance mode and we're only supporting security updates in that branch.
