### ISSUE TITLE
Font size settings have no impact

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#3273]
I am not sure when this started (2.3 or 2.4) but setting the font size settings in _uswds-theme-typography.scss has no impact. Everything is coming up 16px (browser defaults).

My settings:

$theme-body-font-family: "body";
$theme-body-font-size: 7; (should be 18px, but 16)
$theme-body-line-height: 5; (should be 1.62, but 1.15)

**Comment by stphnwlkr** [comment]
After numerous hours of trial and error, the key was setting $theme-style-body-element to true. Is this a new requirement or a bug?

**Comment by thisisdano** [comment]
Let me check on this...

**Comment by thisisdano** [comment]
It's definitely not a new requirement.

**Comment by thisisdano** [comment]
So, the `$theme-body` settings apply only to USWDS components by default, as a level of isolation from existing site styles. 

We set a base font, line-height, and size at the component level, using the settings from `$theme-body-font-family`, `$theme-body-font-size`, and `$theme-body-line-height` as the baseline. For native components, this is the functional equivalent of adding these rules to the `<body>` element.

```html
<body>
  <div class="usa-prose">
    <p>I get the `$theme-body` styles.</p>
  </div>

  <p>I do not get the styles unless `$theme-style-body-element: true`.</p>
</body>
```

You're right, it's only when you set `$theme-style-body-element: true` does this explicitly apply these rules to `<body>`. And this has been the case since `2.0` — perhaps something else in your markup changed so you're only noticing it now?

So I don't think this is new. We tried to isolate by default,  but perhaps there's an argument that the default should change.

**Comment by thisisdano** [comment]
A good trick for initializing any component is to `@include typeset` — this will apply those `$theme-style` default values to the component. Like so:

```
.my-component {
  @include typeset;
  background-color: color("ink");
  color: color("white");
  ...
}
```

**Comment by stphnwlkr** [comment]
Thank you for the reply and explanation. I think I have been using the "settings/ *" files for everything and haven't updated them until recently as I transitioned to using the themes structure. FWIW I do think that the explanation need to be a little clearer - if you change all the other size settings in the uswds-theme-typography file they are irrelevant unless you change this setting. This can be closed
