### ISSUE TITLE
The "here's how you know" accordion doesn't align with Chrome's choice not to display https

### ISSUE THREAD

**Issue by wslack** [uswds/uswds#3281]
<img width="1015" alt="accordian" src="https://user-images.githubusercontent.com/10016577/72471979-aed2a180-37b1-11ea-811b-1991be332de2.png">

## Description

The accordian has text about "https" but there's no visible http:// in the address bar. I wonder if there should be mention of 🔒or something else if this is how other browsers will treat signs that a site has https active.

cc @konklone and @jvehent for their takes as well

**Comment by thisisdano** [comment]
Good point. I can see adding something to the message around a lock image. But I also defer to @konklone on matters such as these.

**Comment by konklone** [comment]
Well, to make it more complicated - Chrome has even indicated [they expect the lock icon to go away over time](https://blog.chromium.org/2018/05/evolving-chromes-security-indicators.html), and only mark sites that are insecure. I do generally expect that's how other browsers will go as well, but there will still be variance on this for at least a while.

My experience is that text updates in the USWDS header take a long time to propagate (if they ever do), so you really want to make them as sparingly as possible, and detecting the browser to make browser-specific messages would make it more likely to fall behind as browsers individually evolve. While the message is a little less clear since it's referencing an `https://` that no longer shows by default, `https://` does show if you click on the URL and it does show in other browsers for now.

I think the message as it stands, since it has a lock icon next to it and `https://` is still something people will come across, is probably good to stay for a while. But if you did make a text update, I'd rewrite the opening to something like:

> When you see a lock symbol or `https://` next to the website name, this ensures...

**Comment by wslack** [comment]
Hmmm. What about changing it only slightly, then, to 

"the **https://** in the full URL ensures that you are connecting....

then again, "URL" is a pretty wordy acronym.

**Comment by konklone** [comment]
Yeah, I thought about using URL (or "location bar") as well, but I think it would be pretty jargon-y for the tone the text is trying to strike for ordinary people. I suspect most folks who know what "URL" means don't need the assistance from this header anyway.

**Comment by buckaroogeek** [comment]
The fragment resonates with me: "My experience is that text updates in the
USWDS header take a long time to propagate".  My experience and observation
concurs with this. One can still find content on my former agencies web
site that was last updated in the 1990s. As a separate issue, I think that
solving or addressing this larger problem would be beneficial and
valuable.  Apologies for the tangent.

brad

**Comment by wslack** [comment]
Not a tangent @buckaroogeek - this is (for me) about what the north star should be, not making everyone change course.

Maybe just saying "the https:// or lock (🔒) signals...."
