### ISSUE TITLE
Create a button group component.

### ISSUE THREAD

**Issue by wbyoko** [uswds/uswds#3348]
## User Story

As a front-end developer, I need a way to group buttons so that it is easier to show associations and improve clarity.

## Considerations

Should the buttons in the button group have space between them or be a single unit?

## Checklist
- [x] Create low-fidelity design
- [x] Review & discuss low-fi design (designer + developers)
- [x] Get user feedback on low-fi designs (optional - if team feels is needed)
- [x] Code
- [x] Conduct usability test with working code (optional - if team feels is needed)

**Comment by jaredcunha** [comment]
I think it would be good to provide the default stying as spaced between, then a variant as joined as a single unit. This makes handling the CSS much easier because you are no long _restoring_ default properties. 

There doesn't seem to be much consistency between designs systems on whether nor not to use both spaced and joined buttons. I personally prefer the semantic value the lists provide for both options. 

Some examples of button groups in the wild:
- [Shopify](https://polaris.shopify.com/components/actions/button-group#navigation)
- [Lightning](https://www.lightningdesignsystem.com/components/button-groups/)
- [Primer](https://primer.style/css/components/buttons#button-groups)
- [Bootstrap](https://getbootstrap.com/docs/4.4/components/button-group/)

Other thoughts:
- Do we provide guidance for `role="toolbar"`? 
- Should we consider an overflow menu for a first release? For a future release?
- Any guidance on using utility classes for spacing?
- What treatments for mobile? Collapse yes or no? (I think arguments can be made for both)

**Comment by Ben-Judy-Flexion** [comment]
Testing upload of design image file:
![Button groups (wireframes) State 1_ default](https://user-images.githubusercontent.com/56978395/76785608-c31c2600-6783-11ea-9984-f465f64f53ce.png)

**Comment by jaredcunha** [comment]
Pull request for documentation site: https://github.com/uswds/uswds-site/pull/892

**Comment by jaredcunha** [comment]
Just want to get some input on some of these questions

Variants included in this release:
- Spaced out buttons (default)
- Segemented list 

**Not included** in this release
- Segmented list with overflow
- Checkbox group
- Radio group
- Vertical organization

Crossed out items about can added as variants in a future release, but what do we think about moving forward with the two variants only at first? Seems button groups in most design systems have it this way, and we can add variants at a later date?

**Comment by jaredcunha** [comment]
@thisisdano After our discussion to support narrow viewports in the separated buttons, I'd like to know your thoughts on some of these options:

We can default to a stacked set until we hit the `mobile-lg` breakpoint. This is also where the  the default buttons change from `width: 100%` to `width: auto`. 
<img width="335" alt="Screen Shot 2020-03-31 at 4 55 55 PM" src="https://user-images.githubusercontent.com/1094951/78074627-0cb66480-7371-11ea-9138-65701dad217b.png">
```
<ul class="usa-button-group">
  <li class="usa-button-group__item">
    <button class="usa-button usa-button--outline">Button</button>
  </li>
  <li class="usa-button-group__item">
    <button class="usa-button">Button</button>
  </li>
</ul>
```
If a designer wants to keep the buttons in a single, they can use the `flex-row` utility. This would essentially force the current behavior we demoed and it the way the component behaves at the `mobile-lg` breakpoint and above.
<img width="335" alt="Screen Shot 2020-03-31 at 5 01 32 PM" src="https://user-images.githubusercontent.com/1094951/78074801-543cf080-7371-11ea-8aa8-18540946923a.png">
```
<ul class="usa-button-group flex-row">
  ...
</ul>
```
After the `mobile-lg` (or if using the `flex-row` utility on viewports narrower than `mobile-lg`), the buttons will automatically wrap like so:
<img width="394" alt="Screen Shot 2020-03-31 at 5 10 33 PM" src="https://user-images.githubusercontent.com/1094951/78075767-22c52480-7373-11ea-913e-72ab8e05ad7d.png">

We can address this in the guidance. 

The segmented variant will always remain in a single row. We indicate that screen width be considered when using segmented lists until we add on an overflow option or smaller buttons.

**Comment by thisisdano** [comment]
I think this is the right path for now — I think the only remaining data point to consider is how this behavior works in the real context of a probable use case for the button group. Let's keep going in this direction, but it would be important to see a more realistic model before finishing up this issue.

**Comment by jaredcunha** [comment]
@thisisdano - I've outlined some possible use case on existing .gov sites for these. The segmented buttons can be used, for example, in toggling a map view. 

<img width="655" alt="Screen Shot 2020-04-07 at 3 20 28 PM" src="https://user-images.githubusercontent.com/1094951/78710571-899e8c80-78e3-11ea-92c3-2ec7c1268c83.png">

While the standard button group can be used on multi-steps forms.  These are are just some screenshots that i've composited together, so some measurements might be 100% here. But this outlines potentional real-world context.

<img width="478" alt="Screen Shot 2020-04-07 at 3 20 17 PM" src="https://user-images.githubusercontent.com/1094951/78710606-9fac4d00-78e3-11ea-8cbf-89987287e24c.png">

**Comment by thisisdano** [comment]
Yes exactly — now my final question is: Given this use-case context, does a stacked-button default for mobile make sense? (I tend to think yes, it does, and this is the proper context in which to evaluate that decision.)

**Comment by jaredcunha** [comment]
@thisisdano For the mobile vew in stacked buttons in [this comment](https://github.com/uswds/uswds/issues/3348#issuecomment-606880869), I showed how you can use the flex utility to override the stacking and keep in a row. 

What I can also do is create a `prioritized` variant that will bump a button up to the top on mobile.  Because it uses flexbox, we can just give a higher `order` value.
```
<ul class="usa-button-group">
  <li class="usa-button-group__item">
    <button class="usa-button usa-button--outline">Cancel</button>
  </li>
  <li class="usa-button-group__item usa-button-group__item--proritized">
    <button class="usa-button">Submit</button>
  </li>
</ul>
```

![Screen Recording 2020-04-08 at 05 10 PM](https://user-images.githubusercontent.com/1094951/78834039-ecfbed80-79bb-11ea-8222-14a317cb8fd0.gif)

If you like that approach, what do you think of the naming? Should it be `--mobile-priority` or something to indicate this is only for mobile? Since the flex utilities are not responsive, we'd have to use the modifier here because we have the unset the order at larger viewports.

**Comment by thisisdano** [comment]
Might it make sense to think about it from the other direction? That is, to put the "logical order" in the markup — in the above example, `Submit` first — then use some other marker (like `order` utilities) to change the order when the buttons are horizontally grouped?

**Comment by jaredcunha** [comment]
I think it depends on the context of the form. Often in multi-step forms, you would see the primary button to the right to indicate forward progress. But with simpler forms, you would see the primary button to the left and along the same axis as the inputs. Which is why I thought of having a way to circumvent that order as an option. 

If that creates confusion, we can disregard the option above and make sure to indicate that primary actions are clearly distinguished from secondary actions.
