### ISSUE TITLE
Proposal: Replace Fractal with Jekyll in the short term

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3378]
In a few months, we're going to want to have a more serious discussion about a long-term strategy for our component library, but in the short term I think we can and should swap out Fractal with Jekyll and proceed from a Jekyll/Liquid base instead of Fractal/Nunjucks.

This would not break existing user-facing functionality and would be continuous with the current canonical HTML format for components. It could be immediately usable and relevant to a project like [`uswds-jekyll`](https://github.com/18f/uswds-jekyll) and would start us more directly down the path of API thinking for our components, templates, and styles. It would also help us get off of Fractal asap and resolve all the headaches that come from relying on that dependency.

I think we could make this transition in a sprint. @mejiaj what do you think? Any considerations I'm missing here?

**Comment by mejiaj** [comment]
@thisisdano, would this use something [Jekyll Styleguide](https://jekyllstyleguide.com/index.html)? Not saying we have to use it, the project itself says it was last updated in 2018.

If we moved to Jekyll, are you saying we would straight up import the components from USWDS instead of importing fractal components like [this](https://github.com/uswds/uswds-site/blob/0735b0dbe58cad38fce3f214fb7011f62d4f920f/_includes/code/components/buttons.html#L12) and the need for this ruby [script](https://github.com/uswds/uswds-site/blob/e86255cfe4178f1684dd5e6e7698d2ee33c973cc/_plugins/fractal_component.rb#L1)?

My main concerns:
- How would we feed components to current USWDS-Site
- Making sure our tests still run properly on USWDS
- Level of Effort on re-writing components that depend on `.config.yml` files or Fractal features to display properly.

I think we can try prototyping this in a sprint and take care of most of these issues. Is it possible to break this task down into smaller, possible more manageable, issues? Something so we could both work on it at once.

**Comment by thisisdano** [comment]
Jekyll Styleguide could be base or guide for this work, but it needn't be. I think we could start with something very simple.

Not sure how it would work with our existing setup, but I want to _start_ by making it mimic the Fractal output as much as possible, so we can use as much of the existing infrastructure as we can (like tests and powering uswds-site).

And yes, definitely, this should be broken into smaller, hours-scope issues. Let's chat about this more if the overall idea passes the smell test!

**Comment by darthmall** [comment]
I hope you can forgive me sticking my nose in, but if you're looking at static site generators in the short term, [11ty](https://www.11ty.dev/) might be worth a look. You could keep your nunjucks templates and it doesn't introduce another language dependency; it's JavaScript, so it should work with the node tools you're already using.

**Comment by thisisdano** [comment]
Thanks @darthmall I'll add it to the list — it's been on my radar recently though I've never used it.

**Comment by thisisdano** [comment]
Loved using 11ty, but for the short term we will be using PatternLab. More to come in subsequent issues.
