### ISSUE TITLE
Fractal controls not working

### ISSUE THREAD

**Issue by darthmall** [uswds/uswds#3382]
## Description

None of the JavaScript navigation in Fractal is working for me with a clean checkout. I can't toggle folders in the sidebar, switch tabs ("HTML", "Notes", _etc._) in the component, and I can't resize any of the panes.

## Steps to reproduce the issue

1. git checkout git@github.com:uswds/uswds.git
2. npm install
3. npm start
4. Open localhost:3000
5. Click the toggles in side bar
6. Select a component
7. Grab either resize handle and drag

## Additional information

I've got another project where I'm using Fractal 1.2.1 (same as you) and I'm not having the same problem, so I'm not sure if this is an issue with Fractal or not. I've tried this with both Chrome & Firefox, and Node 10 & 12.

<dl>
<dt>Operating System</dt>
<dd>macOS 10.14.6</dd>
<dt>Node</dt>
<dd>12.16.1</dd>
<dd>10.16.3</dd>
<dt>Firefox</dt>
<dd>74.0.1</dd>
<dt>Chrome</dt>
<dd>80.0.3987.149</dd>
</dl>

**Comment by thisisdano** [comment]
Yeah, we'd disabled all the js in fractal because we were getting dinged for an out-of-date jQuery dependency that I couldn't figure out how to update and ran out of patience and, as they say, just "nuked it from orbit". We're working to switch out Fractal for something else in the very near term and will hopefully have this resolved in a couple weeks.
