### ISSUE TITLE
Determine breadcrumb component elements to include in an API

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3410]
Determine what breadcrumb elements to include in an API

**Comment by mejiaj** [comment]
Some initial thoughts:
- Vertical spacing on breadcrumb
- Horizontal spacing between breadcrumb items
- Breadcrumb separator *

* How would we allow users to be able to enter a unicode character like `◆` but also an SVG using the `add-background-svg` mixin.

Usually in using unicode characters they have to be passed through something like:
https://www.evotech.net/articles/testjsentities.html

Otherwise it can cause rendering issues on older browsers. Is that something we would add in guidance?

**Comment by pglevy** [comment]
I'm concerned about the default to SVG for the breadcrumb separator. As these examples with two of the default typefaces show, we lose a lot of the typographical harmony you get from using the font's characters when going with a single icon. What are your thoughts, @thisisdano ?

- [Merriweather](https://codepen.io/pglevy/full/ZEbRBZj)
- [Public Sans](https://codepen.io/pglevy/full/NWGzdqw)

![image](https://user-images.githubusercontent.com/5177337/81596191-a2daa300-9391-11ea-892c-13bbdac81fa1.png)

![image](https://user-images.githubusercontent.com/5177337/81596209-aec66500-9391-11ea-99da-c6f73a4c050f.png)

**Comment by maya** [comment]
@pglevy I'd expect it to be consistent with the other components on the site which use the thinner chevron arrow.

<img width="177" alt="Screen Shot 2020-05-11 at 5 22 06 PM" src="https://user-images.githubusercontent.com/5249443/81624824-0671ca00-93ac-11ea-8ce8-aa0a2a9b97c3.png">

**Comment by pglevy** [comment]
Fair point, @maya! I updated [this mockup](https://codepen.io/pglevy/pen/ZEbRBZj) to include the icon from the current version. I still think it loses some of the personality of the typeface. Is the concern that characters using UTF-8 encoding won't render properly? Or just a stylistic preference?

**Comment by thisisdano** [comment]
I have a strong preference for a common separator that's clear and consistent regardless of the type treatment. There is some possibly that different faces will take a different approach to the `>` character — some clearer and some less clear. While a common separator sacrifices something of the tone of the typeface, I think that's a feature not a bug, since the breadcrumb isn't a sentence, it's a sequence.

**Comment by thisisdano** [comment]
Subject to change, but completed in #3451 

#### Settings options
Setting | Usage | Default
--- | --- | ---
`$theme-breadcrumb-back-icon` | The path to the **back** icon, relative to the CSS output | `"#{$theme-image-path}/arrow-left.svg"`
`$theme-breadcrumb-back-icon-aspect` | The aspect ratio of the **back** icon, expressed as a list in the form `[width], [height]` | `1, 1`
`$theme-breadcrumb-font-size` | The size of the breadcrumb text | `"sm"`
`$theme-breadcrumb-font-family` | The family of the breadcrumb text | `"body"`
`$theme-breadcrumb-gap` | The space between indicator icons and text | `1.5`
`$theme-breadcrumb-icon-color` | The color of indicator icons | `"base"`
`$theme-breadcrumb-link-colors` | The color of breadcrumb links in the form `[link], [hover], [active]` | `"primary", "primary-dark", "primary-dark"`
`$theme-breadcrumb-min-width` | The width at which the breadcrumb displays the full breadcrumb list | `"mobile-lg"`
`$theme-breadcrumb-separator-icon` | The path to the **separator** icon, relative to the CSS output | `"#{$theme-image-path}/angle-arrow-right.svg"`
`$theme-breadcrumb-back-icon-aspect` | The aspect ratio of the **separator** icon, expressed as a list in the form `[width], [height]` | `38, 64`
`$theme-breadcrumb-spacing-bottom` | Spacing below the breadcrumb | `2`
`$theme-breadcrumb-spacing-top` | Spacing above the breadcrumb | `2`
`$theme-breadcrumb-wrapping` | Controls whether the breadcrumb wraps or truncates | `false`
