### ISSUE TITLE
Using `usa-current` on child links mis-styles desktop links

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3421]
When using `usa-current` to have a current page indicator on mobile nav child links, you get this weird line on desktop.

<img width="331" alt="Screen Shot 2020-04-15 at 11 44 04 AM" src="https://user-images.githubusercontent.com/11464021/79778397-86e16580-82ed-11ea-9552-2b739bdd7332.png">

**Comment by mejiaj** [comment]
@thisisdano should this go away on desktop or do we need to come up with a new style for current links on desktop?

**Comment by mejiaj** [comment]
@thisisdano I noticed the extended version shows the `usa-current` styles on desktop when subnav is active, but header basic does not. Is this intentional or are they supposed to look the same?

This is primary nav on desktop with `usa-current`.

Header basic
![image](https://user-images.githubusercontent.com/3385219/80141077-9a4f3380-856e-11ea-8d75-37c9aa6b89c2.png)

Extended
![image](https://user-images.githubusercontent.com/3385219/80141046-899ebd80-856e-11ea-8f2b-757e58d635e1.png)

**Comment by thisisdano** [comment]
I don't think this is intentional

**Comment by mejiaj** [comment]
Would the correct behavior be to show the line on primary nav items and when subnav is shown it's also hidden?

**Comment by thisisdano** [comment]
Yeah, I don't think the indicator should show in addition to the dropdown. The indicator should vanish when the dropdown is active.

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds/pull/3438
