### ISSUE TITLE
Accordion needs  "expand all'' functionality

### ISSUE THREAD

**Issue by bruce-usab** [uswds/uswds#3435]
- [x] **@thisisdano New issue is created #3654 with original issue linked. I'd like to close this ticket and use the new ticket to track further work.**

## Accordion feature request:  Accordion component really needs some kind of expand all functionality.

http://designsystem.digital.gov/components/accordion

Accordions facilitate scanning a page, but they need to be used with caution because they break search and wreak havoc with off-line uses of content.

Example of accordion breaking search:
- Search engine returns a hit for term which is hidden in an accordion.  The context might not display in the search engine UI or following the link lands the user at a seemingly random place on the page.
- The in-browser find-on-the-page feature (typically Ctrl-F) will not display content in a closed accordion.

Examples of accordion breaking off-line uses:
- Printing the page typically does not include content inside accordions
- Saving the page or copying to word processor document may not render accordion content

## Description

My expectation is that the USWDS accordion component would include a promient feature to expand all accordion content all at once.  Of course, there should be an easy way to reset (collapse) accordion content as well.

As one example, that does a good job with this, please see the WCAG Quick Reference.
https://www.w3.org/WAI/WCAG21/quickref/

## Steps to reproduce the issue

1. Use the USWDS Accordion Component as-is.
2. If you have more than one accordion on the page, you have just created a problem for your users!

## Additional information [optional]

- Discussion 4/24/2020 on GSA Section508 listserv

**Comment by gillick** [comment]
Hey, however these accordions stop breaking search is fine with me. Lots of feddy content is reference material that folks are looking for. Breaking search is counter-productive.
 
Once upon a time, a person could use a search engine to find content (e.g., [a search for the text of a Constitutional amendment](https://www.google.com/search?q=No%20Soldier%20shall,%20in%20time%20of%20peace%20be%20quartered%20in%20any%20house,%20without%20the%20consent%20of%20the%20Owner,%20nor%20in%20time%20of%20war,%20but%20in%20a%20manner%20to%20be%20prescribed%20by%20law.%20site%3Adigital.gov&cad=h)), click through to [a page chosen from a list of search-solutions](https://designsystem.digital.gov/components/accordion/), and then (if the page was lengthy and full of text) that person might ctrl-f and find that content.
 
Fed versions of accordions (and yes, I’m counting [the Read More variety found on USAJobs.gov](https://www.usajobs.gov/GetJob/ViewDetails/566393300)) either don’t penetrate the accordion to find the text or find the text but don’t reveal it (“Ha! It’s somewhere on the page, but I won't tell you where!”) to the user.

**Comment by afeijoo** [comment]
Some additional feedback I received via email: 

* Accordions make information difficult to find because a person has to know which accordion to open to find the content they are seeking.
* Accordions make information even more difficult/impossible to find for users with accessibility issues because screen readers can't see the information unless the accordions are expanded.
* If accordions can't be removed, we recommend the use of "Expand All" buttons.
* We will continue to discourage their use at `FederalAgency`.

**Comment by bruce-usab** [comment]
Did the accordion component benefit from PR2604 the more accessible focus style?

**Comment by mejiaj** [comment]
@bruce-usab , did you mean this outline or something else?

![image](https://user-images.githubusercontent.com/3385219/81184065-91e6f780-8f75-11ea-84af-f884d68be1f4.png)

**Comment by bruce-usab** [comment]
@mejiaj if you give the keyboard focus to the "component code" header, you will see the light blue (cyan) border right against the dark (navy) blue field.  There is not much contrast between the two blue colors.  I am looking for a the white gap shown in #2604.

**Comment by mejiaj** [comment]
Buttons and `.usa-accordion__button` have an outline offset of `0`. You'd have to override that value.

```scss
.usa-accordion__button:focus {
  outline-offset: 2px;
}
```

![image](https://user-images.githubusercontent.com/3385219/81189028-b0e88800-8f7b-11ea-86a2-bc3b36223a43.png)

**Comment by bruce-usab** [comment]
@mejiaj i am asking about how to add alt text to image i just pasted into my github comment above?

Agreed, alt text in markdown is not a problem.

**Comment by bruce-usab** [comment]
Thanks @mejiaj, i added alt to my screen capture!

**Comment by bruce-usab** [comment]
Thanks so much for the conversation so far!
I wanted to add that the WAI QuickRef has the same basic find-ability issues as with other accordion implementations.  Namely:
* Ctrl-F (find from the browser) only works if one uses Expand All first.
* Results from a [google search](http://google.com/search?q=%22content%20is%20primarily%20intended%22%20site%3Aw3.org/wai/wcag21/quickref) show a hit, but following the link one does not see the hit

**Comment by gillick** [comment]
Not to beat-up Bruce's suggestion, because it's actually a pretty good feature, I'm not certain that it properly solves the ctrl-f problem.

Ctrl-f (find) should work "out of the box" -- absent additional knowledge of how (differently) dot-gov sites work. Find should just "find" the content. If content is in an accordion, the accordion should just open and your cursor should land properly. Find should just work.

Between this and other little oddities, I find myself wondering if we're practicing a sort of "Federal websites should work like each other, but not necessarily like other, real-world websites" design philosophy. I hope that's not the case; but I'll be reminded of it, the next time I see a dot-gov page littered with  icons and they mean something different from Outlook, Gmail, Google Analytics, Google Data Studio, the NYTimes app, IFTTT app, LastPass, and Islandora -- not that I'm keeping a list...

**Comment by nks-bix** [comment]
From MegB:

Because accordions function much in the same ways as filters with drop-down boxes, you can copy the effort of a filter box you've done. You will want it to announce what it is, as well as the state of the item (list/toggle button opened or closed) based on what is done with the toggle, so that a blind user can understand how to move through the information when the item is opened. Toggle state: open* i will check my JAWS sheet to see what it ts called there.

Visually, the hover state as well as one other indicator should be there to show that it is indeed an accordion with hidden but reveal-able information. This can be a combination of any of the following:

hover state changes to show the contents of the accordion, box changes color to indicate that it is clickable, on page context (copy text) gives instructions of how to operate the accordion buttons.

**Comment by afeijoo** [comment]
USAgov has an option to `Open All` and `Close All`. See, for example, https://www.usa.gov/help-with-bills.

**Comment by bruce-usab** [comment]
Very nice!

**Comment by jAigret-Bix** [comment]
Issue needs review and grooming. 

-We need to refine the prototype I made to create the expand/collapse (JS required)
-Do we update the Accordion guidance with the references people posted? (Use of Accordions is discouraged and if you must use... keep them open at the start)

**Comment by chazchumley** [comment]
@jAigret-Bix I tested the issue reported above and was able to verify the following:

- Content within a collapsed accordion cannot be searched
- Content within a collapsed accordion cannot be printed.

I agree that an expand all function would help in partially resolving the issue.  However, guidance should also be updated to state the cons of using an accordion and the specific use cases for when to use an accordion.

**Comment by jAigret-Bix** [comment]
New issue created #3654 with original issue linked.

**Comment by jAigret-Bix** [comment]
@thisisdano  New issue created #3654  with original issue linked. I'd like to close this ticket and use the new ticket to track further work.

**Comment by thisisdano** [comment]
OK, moving to #3654
