### ISSUE TITLE
Conduct initial user testing using breadcrumb mockup/prototype

### ISSUE THREAD

**Issue by pglevy** [uswds/uswds#3459]
Validate initial assumptions about experience and expectations for both site visitors and Design System users.

[Test Plan](https://github.com/uswds/uswds/wiki/Breadcrumbs-User-Testing-Plan)

**Comment by pglevy** [comment]
@thisisdano , let me know if that updated [test plan](https://github.com/uswds/uswds/wiki/Breadcrumbs-User-Testing-Plan) is aligned with what you're thinking. I added some questions for system users and would still need to compile a prototype for use with those questions. Also updated the end users tasks to use govt sites instead of commercial. Thanks.

**Comment by nks-bix** [comment]
User [feedback is being collected](https://app.slack.com/client/T025AQGAN/C3F14AHSQ/thread/C3F14AHSQ-1590680691.446900) through the next week or so and will be considered for use in crafting the [breadcrumb component guidance](https://github.com/uswds/uswds/issues/3407).

**Comment by afeijoo** [comment]
I'm capturing Katie's feedback on the breadcrumbs guidance here:

1. **The IA note ended up needing context.** When it was added to the bullet about wrapping, the note about revisiting the IA like an afterthought compared with the message of the rest of the guidance, which prompted me to want to add some additional context. I even considered adding a note about the use of a sitemap as an approach for ensuring there were no orphaned pages and allowing for easy evaluation of site depth. However, the guidance then started to feel like it was going above and beyond (and branching out into content strategy territory) what was intended in this first iteration. Rather than force the content to fit with the rest of the message for that bullet, I wanted to check in with you to see if you think it would be best to leave this to be revisited for a later iteration? Here is what that paragraph might look like if the IA sentence was included:

> **Avoid wrapping.** If a website contains many levels of hierarchy, it can become overwhelming and cumbersome to display the full breadcrumbs – even at larger widths. Consider setting the min-width token to a larger screen size and avoid wrapping for deep sites. For particularly deep sites, consider revisiting the information architecture as an approach for avoiding wrapping.
 
2. **The matching title bullet brought up a consideration around CMSs.** When describing that the title for the link in the breadcrumbs should match the page title, I noted this is often something that can be configured in the CMS (the breadcrumbs are pulled from the title field of pages automatically which would ensure if the page title is ever updated, the breadcrumbs are updated as well). Perhaps something to discuss later?
 
3. **The guidance purposefully excluded any mention of SEO considerations.** This was brought up in our meeting but I wanted to include in the comprehensive notes here for our records. One example: The benefits of breadcrumbs are not only for the UX of the site but also used by search engines to determine site structure – the better the site structure, the higher the page ranking.
