### ISSUE TITLE
Nested list has top margin when $theme-global-content-styles is true

### ISSUE THREAD

**Issue by jonraedeke** [uswds/uswds#3476]
#3078  Description

When setting `$theme-global-content-styles: true;` the following styles are added:

```
.usa-list, .usa-prose>ol, .usa-prose>ul, ol, ul { margin-bottom: 1em; margin-top: 1em; line-height: 1.5; padding-left: 3ch; }
.usa-list:last-child, ol:last-child, ul:last-child { margin-bottom: 0; }
```

This causes awkward spacing in nested lists:

<img width="197" alt="Screen Shot 2020-05-18 at 3 30 59 PM" src="https://user-images.githubusercontent.com/2054715/82252264-b7341800-991c-11ea-92f8-779d00d6e48b.png">

**Comment by mejiaj** [comment]
@thisisdano what would be the expected behavior here? Would there 0 spacing on the nested list like this?

![image](https://user-images.githubusercontent.com/3385219/83429031-0f791880-a3f9-11ea-9697-122f4b2f24f2.png)

---

Or would nested list items have a `margin-bottom: 0.25em;` like this?

![image](https://user-images.githubusercontent.com/3385219/83429164-43ecd480-a3f9-11ea-9748-430965a9a2e5.png)
