### ISSUE TITLE
Change to layout_grid.css breaks grid

### ISSUE THREAD

**Issue by AlejandroColinaGSA** [uswds/uswds#3537]
## Grid broken

I have a grid that how collapses unto itself and grid-col content overlaps each other

## Steps to reproduce the issue

- create a standard grid with several columns in the same row
- in each column have some text
- make the window smaller. You'd expect to have the grid items collapse into rows but instead the simply squish together

## Additional information 

The source appears to be this change:

* https://github.com/uswds/uswds/commit/64b6e4c52a99fb704fb25a7ae0017223e8606204

**Comment by mejiaj** [comment]
What version of USWDS are you on? 

We've made changes recently to grid for better compatibility with IE11. We used [this](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/components/preview/flex.html) to test.

Can you share the grid classes or markup you used?

**Comment by AlejandroColinaGSA** [comment]
Hi, the code in question is here:

https://federalist-0ad5a602-ca98-4a7e-8d6e-d9ece7bc4cf8.app.cloud.gov/site/gsa/sam-styles/components/detail/button--default.html

If you inspect one of the grid-col divs and turn off this line "min-width: 1
px;" you will see that it works.

[image: image.png]

I am not sure

*J. Alejandro Colina*202.539.6080
Web Developer
Team Prespecta
(BasecampCS)

**Comment by mejiaj** [comment]
Thanks for your input! Removing `min-width: 0;` gives you the desired output. But I don't think that resolves IE11.

I added your example to our flex test here:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-nested-flex/components/preview/flex.html

IE11 without `min-width: 0;`.
![image](https://user-images.githubusercontent.com/3385219/86944977-1557cd00-c10e-11ea-9ea1-f2a77a3e69f9.png)

**Comment by mejiaj** [comment]
I've added more tests [here](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-nested-flex/components/preview/flex.html#issue-3537). Including some potential crossbroswer solutions in the meantime.

Like I mentioned before, removing `min-width: 1px` only affects modern browsers. IE11 will still look broken. What I've noticed is the root of the issue seems to be the `flex-basis: 0%` value in the flex shorthand (the 3rd value).

Part of the reason why it's `0%` is to prevent content from overflowing out of the document.

---

I don't think we need `min-width: 1px` anymore, but we'll need to decide on the best "default". Because just removing it and having nested elements not work in IE11 doesn't seem like an ideal solution.

**Comment by thisisdano** [comment]
After further testing, I think we've determined that this is a problem without a good solution, only a matrix of flawed solutions. As long as we support IE11, we're not going to make any code changes to address this it. Using `grid-col` is good for most single-row solutions, but unreliable the layout requires wrapping. Using a fixed percentage column like `grid-col-4` or a column set to fit, like `grid-col-auto` should fix the wrapping and overflow issue and might cause the least regression to your layout. Good luck
