### ISSUE TITLE
Combobox not initialized reliably in React app

### ISSUE THREAD

**Issue by pullias** [uswds/uswds#3599]
## Description
I am trying to use the combobox in a react app which displays the form page, then after form submission a different page is shown before the form page is shown again.   
The first time the combobox works correctly but the next time the combobox displays as a drop down list.  
 I understand some JS initialization is not happening the second time the combobox is added to the DOM and would appreciate some guidance on how to fix this.

## Steps to reproduce the issue

1. https://codepen.io/pullias/pen/PoNpjZN
2. Select an item in the combo box and use button to go to page 2
3. Press button to go to page 1

EXPECTED
Combobox works correctly the second time

ACTUAL
Combobox works as a plain ``<select>`` element the second time

**Comment by RafterGit** [comment]
Noting I'm seeing this behavior as well in my implementation. @pullias  have you been able to find any workarounds for this?

**Comment by pullias** [comment]
@RafterGit No, I gave up on Combobox and rolled my own React component for the input.

**Comment by thisisdano** [comment]
@wbyoko Do you have any insight here?

**Comment by RafterGit** [comment]
> @RafterGit No, I gave up on Combobox and rolled my own React component for the input.

Thank you for replying @pullias , I'm going to do a little bit more troubleshooting but `rect-select` looks like the way to go at the moment.

**Comment by scottqueen-bixal** [comment]
@pullias I was taking a quick look at your example and I think this is a case where we might want to reach for the [USWDS primary component methods](https://designsystem.digital.gov/documentation/developers/#js-customization) and wrap it in a `useEffect`.   

Here is a [updated `comboBox` based on your example in a CRA](https://github.com/scottqueen-bixal/uswds-combo-box-example/blob/master/src/App.js).

**Comment by Swimburger** [comment]
@scottqueen-bixal, we're trying to componentize USWDS components using React, including combo box.
We are using effects to initialize and clean up the combo box, but we can't use `document.body` as the ref since that would change things outside of the React component and if multiple instances of the components were to be created, it would invoked `comboBox.on` multiple times.
 
Unfortunately, passing the combo box element to `comboBox.on` does not work. Similar to some other components, you have to pass in `document.body` or it doesn't work. 

How should we approach this?

(It's essentially the same issue as #4300 and the same issue will probably occur as I continue to build this component library)

**Comment by brunerae** [comment]
Potentially resolved in 3.0 Beta; need to investigate.

**Comment by brunerae** [comment]
Fixed in USWDS 3.0 Beta.
