### ISSUE TITLE
Tooltip positioning

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#3915]
When using the tooltip component data-position="top" or "bottom" the tooltips do not adjust for spacing. Left and right positions will change sides when there is not adequate space to render properly.

### data-position="top"
https://user-images.githubusercontent.com/1405187/103180491-1cad9700-4864-11eb-8890-3cda6360498c.mp4

### data-position="left"
https://user-images.githubusercontent.com/1405187/103180608-326f8c00-4865-11eb-9751-c6b721747ed2.mp4

**Comment by jennyychaa** [comment]
@stphnwlkr can you provide more details on the results you are hoping to see? Digging into the code a little bit (`js/components/tooltip.js`), it seems like this is expected behavior for tooltips to adjust their positioning if necessary. This is my understanding thus far: 

- **data-position="top"** - If the element is clipped out of the viewport, position to bottom; otherwise, position to top.
- **data-position="bottom"** - If the element is clipped out of the viewport, position to the top; otherwise, position to bottom.
- **data-position="right"** - If the element is clipped out of the viewport, position to left or top depending on the size. Otherwise, position to top.
- **data-position="left"** - If the element is clipped out of the viewport, position to right or top depending on the size. Otherwise, position to top.

I also tried to replicate the bug from your first video, where the words are overflowing out of the black container but I haven't been able to see the issue on my end. Please see the screenshot below. 

<img width="642" alt="Screen Shot 2021-01-12 at 7 34 48 PM" src="https://user-images.githubusercontent.com/16579792/104391180-5a214e00-550d-11eb-8f13-89ae82ea1b79.png">

Any additional information would be helpful. Thank you!

**Comment by jAigret-Bix** [comment]
Dev review w Dan & team 2/16

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds/pull/4062
