### ISSUE TITLE
Add input prefix and suffix

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3939]
Code: https://github.com/uswds/uswds/pull/3999
Documentation: https://github.com/uswds/uswds-site/pull/1154

TODO
- [x] First code review (@thisisdano)
- [x] Check heading order (@thisisdano)
- [x] First guidance review (@thisisdano)
- [x] Second code review (@mejiaj)
- [ ] Further dev review (_optional_)
- [x] Merge code into `uswds-2.11.0`
- [ ] Second guidance review (@katieekline)
- [ ] Further content review (_optional_)
- [x] Link guidance to `uswds-2.11.0` (@thisisdano)
- [x] Update guidance to new formatting (@thisisdano)
- [x] Merge guidance into `uswds-2.11.0-docs`
- [ ] Update design assets if necessary (@thisisdano)

- - -

Additional cue for site visitors to quickly know that this is a "money" field or a "percent" etc.

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback - done 1/25
- [x] 20% - Draft user story & clarify the problem(s) / user needs
- [x] 30% - Low-fi design review
- [x] 40% - Get community feedback on initial, Hi-fi designs
- [x] 50% - Hi-fi Sketch assets review
- [x] 60% - Hi-fi Adobe XD assets review
- [x] ~80% - Sketch and XD assets review w/ Dan + merged into master working files~
- [x] ~100% - PR approved by Dan~

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews)- done 1/26
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done 1/26
- [x] 40% - Get community feedback on draft guidance
- [x] 50% - Draft guidance review no. 2 (accessibility focus)
- [x] 60% - Draft guidance review no. 3 (w/ Dan)
- [x] ~80% - Add component to research report and slide deck~
- [x] ~100% - PR approved by Dan~

CODE
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [x] 40% - Get community feedback or conduct tests with users, round 1
- [x] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [x] 80% - Get community feedback or conduct tests with users, round 2
- [x] ~100% - PR approved by Dan~

**Comment by npage123** [comment]
Reviewed existing patterns from Material Design, gov.UK, Mailchimp, gofundme, calfresh, and Bootstrap and placed in Prefix and suffix text inputs Figma file. Discussed with Jared that prefix and suffix options should just be variants of the existing text input component. We both prefer where the focus state encompasses the whole input box and not just the editable area within the input. Examples below.

Preferred
![Screen Shot 2021-01-26 at 9 35 21 AM](https://user-images.githubusercontent.com/12956624/105867164-62bc5e80-5fba-11eb-8766-191dc74f86f5.png)

Not preferred
![Screen Shot 2021-01-26 at 9 32 42 AM](https://user-images.githubusercontent.com/12956624/105867151-5f28d780-5fba-11eb-946f-c44b2b5f3b44.png)

**Comment by jaredcunha** [comment]
We can use Javascript to deliver the preferred focus state, which the not preferred type can be a fallback where that JavaScript fails.

**Comment by npage123** [comment]
Found some research on why the gov.UK design system did what they did with their prefix and suffix input icons - https://github.com/alphagov/govuk-design-system-backlog/issues/134

A few things stood out:

Some browsers have extensions that add their own icon to an input which may appear in the same location of a prefix or suffix icon therefore making the icon unreadable.

Due to the prefix and suffix being in their own box with a light gray background, some users reported as thinking that the gray box was a button to change currency (£, $, € etc). Because of this, many services changed the gray background to clear. Another suggestion was made to make the click area include the prefix or suffix box which is what we anticipate doing but not visually separate it. Focus would be the entire item (including the prefix or suffix icon and input) which would have a border around it, remove the border from the actual input, and place the cursor justified left (after a prefix icon if one is there).
