### ISSUE TITLE
Add derivative works language to license.md

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds#3945]
- [ ] Add OGC provided _Derivative Works_ language to license.md file [https://github.com/uswds/uswds/blob/develop/LICENSE.md](https://github.com/uswds/uswds/blob/develop/LICENSE.md)
- [ ] Consider directing visitors to license.md link from Icons page

**Comment by ardenk** [comment]
@jaredcunha here's the language to add:

**Section 1 - Copyright Ownership of Works Created by U.S. Federal Employees**
This repository contains both the original icon design for Material icons (the “Work”, as defined in Section 1 of the Apache 2.0 License) and modifications made by the General Services Administration (GSA). This repository combines the Work and these GSA modifications into a font design called [insert name], which is a “Modified Version” of Material.
As a work of the United States Government, the software modifications made by GSA are not subject to copyright within the United States. Additionally, GSA waives copyright and related rights in its software modifications worldwide through the CC0 1.0 Universal Public Domain Dedication (https://creativecommons.org/publicdomain/zero/1.0/).
The Work (as defined in the Apache 2.0 License) remains subject to copyright under the Apache 2.0 License.
This Modified Version ([insert name]) contains both design elements under the Apache 2.0 License and design modifications by GSA released as CC0. It is a “joint work” made of the icon set and modifications combined into a single work.

**Section 2 - Trademark**
GSA owns, reserves, and retains all rights, title, and interest in all trademarks owned by GSA. The User does not acquire any right or interest of any kind in any GSA trademark because of their use of the Modified Version or any of the modifications made to the Work by GSA.

**Comment by jaredcunha** [comment]
@ardenk @jonadecker Does this content belong under any of the existing headings in [LICENSE.md](https://github.com/uswds/uswds/blob/develop/LICENSE.md)? If so, which?

Then in the post above, should **Section 2** be nested under **Section 1** or are they at the same level?

**Comment by ardenk** [comment]
@afeijoo see Jared's question above
