### ISSUE TITLE
Research testing options, omit Fractal

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3998]
LOE: 1 week 

Currently tests via `gulp test` don't run in new pattern library because of missing fractal dependency via [fractal.config.js](https://github.com/uswds/uswds/blob/develop/fractal.config.js).

1. Uncomment [line 4 of gulpfile.js](https://github.com/uswds/uswds/blob/library--develop/gulpfile.js#L4) in `library--develop` branch
2. Run `gulp test`
3. View error 
```
[13:06:45] Using gulpfile ~/web/uswds/gulpfile.js
[13:06:45] Starting 'test'...

✖ ERROR: Error: Cannot find module '../fractal.config'
…
```
---

- [ ] Research  headless testing framework
- [ ] Discover what works w PL, How can you spin up a PL version in memory. 
- [ ] Do we need to build our own? what would that entail? 

**acceptance criteria**
- [ ] solution to unit testing
- [ ] create unit testing plan and timeline
- [ ] create issues for next steps and implementation

**Comment by scottqueen-bixal** [comment]
Picking this up, will take a look into our testing suite and see how we can configure it to integrate it with our patternlab workshop.

**Comment by sarnikbixal** [comment]
After researching options for testing I feel we should go with Cypress.io for spinning up a headless browser and axe testing.

I looked at both selenium and cypress and although selenium is more powerful and has more features, it has a steeper learning curve and the extra features do not really pertain to our case. Of those being able to spin up headless IE, and multiple tabs. 

Cypress has been gaining support to add IE testing in the future and I think that since we currently don't do headless testing on IE, we lose no functionality. 

Cypress also has an axe-core library that is widely used and seems easy to implement and import our config settings.

Next steps would be to setup a cypress build configuration then modify our tests with cypress syntax (very easy to read).

For CircleCI we will need to run our pattern-lab instance on the server, then tear it down. Previously Fractal ran a local instance on a built in node server. Since we have Node.js on our CircleCI we should have no problem running a local pattern lab instance on a port of choice for the headless browser to attach its-self too.

We can still use mocha-chai for the unit testing of components, this is mainly for axe and regression testing.

Sources:
https://www.cypress.io/
https://www.npmjs.com/package/cypress-axe

**Comment by scottqueen-bixal** [comment]
yes, this was closed with,  https://github.com/uswds/uswds/pull/4071

**Comment by jAigret-Bix** [comment]
This issue is complete with #4071 and can be closed @thisisdano
