### ISSUE TITLE
Gov banner initializer script prevents banner from opening for 8 seconds

### ISSUE THREAD

**Issue by maya** [uswds/uswds#4033]
### Describe the bug
After installing the initializer script, the gov banner doesn't open until 8 seconds later

### Steps to reproduce the bug
1. Go to https://cdcgov.github.io/SimpleReport_Public_Site/
2. Click on gov banner button
3. Observe it doesn't open
4. Wait 8 secs and it opens

### Expected behavior
I expect it to be able to open after the page loads.

### Screenshots

https://user-images.githubusercontent.com/5249443/109193652-755abc80-774d-11eb-831a-6c3a4c49aeb3.mp4

### System setup
- **USWDS version:** 2.10.1
- **Device:** MacBook
- **Operating system:** Mac Big Sur
- **Browser and version:** Latest Chrome

**Comment by thisisdano** [comment]
The initializer will prevent the banner from opening until it notices that the USWDS javascript has loaded. Is there something on this site that might be delaying that JS? If you remove `uswds-init`, does it work as expected without the delay?

**Comment by maya** [comment]
It was opening normally before adding it which you can view here: https://simplereport.gov/

I've not dug into any of the JS yet, here is the scripts file: https://github.com/CDCgov/SimpleReport_Public_Site/blob/main/_includes/scripts.html

**Comment by thisisdano** [comment]
I'll pass this along to someone with more domain expertise, but I haven't seen anything like this yet. Does it make any difference if you remove the `async` attribute from your `script` tag? Since you already include it at the bottom of your body element, the `async` may be less necessary

**Comment by thisisdano** [comment]
And is this using the uswds.js.min from `2.10.0` or later?

**Comment by thisisdano** [comment]
Yeah, I don't see the `uswdsPresent` string in your `uswds.js.min` — this may indicate that it's an older JS file, and this may be why you don't see any functionality until after init times out.

**Comment by maya** [comment]
I just updated the JS file but no change in behavior.

**Comment by maya** [comment]
Changing async to false in the file fixed it. This is the jekyll uswds template btw so you'll probably need to fix it there.

**Comment by aduth** [comment]
I was curious to check on this since I'd proposed some changes to this initializer script in #4243 and wanted to account for any potential regressions or fixes it might introduce.

I wasn't able to reproduce this in the current version of the Jekyll USWDS template, but I checked out the referenced repository and could reproduce at the commit immediately preceding the USWDS upgrade in https://github.com/CDCgov/prime-simplereport-site/commit/b91576e17c2bd86cd76e4c58985b760b148aeee4 (https://github.com/CDCgov/prime-simplereport-site/commit/5f95c6d7290caf969c29646aa6283aeccf00cafb), but not after upgrading. Could it have possibly a browser cache or build issue which had caused a stale copy of the older version to stick around? Otherwise I think the version mismatch hypothesis in https://github.com/uswds/uswds/issues/4033#issuecomment-786198837 would explain it.

Since the initializer script does polling to check whether the main script is loaded (prior to #4243), I wouldn't think using `async` to load the main script should make a difference.

**Comment by maya** [comment]
Not exactly sure, but if you confirmed that it's working on the current Jekyll version, then happy to close this.
