### ISSUE TITLE
Duplicate .zip file in uswds-2.10.2

### ISSUE THREAD

**Issue by mchelen-gov** [uswds/uswds#4070]
### Describe the bug
When downloading the [2.10.2 zip file](https://github.com/uswds/uswds/releases/download/v2.10.2/uswds-2.10.2.zip) there is a duplicate .zip file contained inside it.

### Steps to reproduce the bug
1. Download https://github.com/uswds/uswds/releases/download/v2.10.2/uswds-2.10.2.zip
2. Extract zip
3. Open directory `uswds-2.10.2`
4. In addition to the [documented](https://github.com/uswds/uswds#download-and-install) files and directories there is also a `uswds-2.10.2.zip` file.

### Expected behavior
Extracting release zip provides [documented](https://github.com/uswds/uswds#download-and-install) assets and no additional .zip files.

### Screenshots
![image](https://user-images.githubusercontent.com/63597655/109992096-edd6f580-7cd8-11eb-88d8-8beb8533f81d.png)

### System setup
- **USWDS version:**
- 2.10.2 
- **Device:**
- Desktop
- **Operating system:**
- Ubuntu 20.04
- **Browser and version:**
- n/a

### Additional context
The 2nd zip file seems to contain the same directories and assets except for missing the `scss` and `js` dirs. Is this an intentional behavior?

**Comment by thisisdano** [comment]
Thanks, we see that. We'll probably publish another patch release to remove it, since we can't update the ZIP without affecting the security hash. We're also working to fix our release script to prevent this in the future. 

The "inner" zip was an early zip of the release that didn't zip properly and was included in error. It's incomplete, as you correctly note!

**Comment by mchelen-gov** [comment]
Understood, thanks for the quick reply & confirmation!
