### ISSUE TITLE
Uncaught TypeError: t.target.closest is not a function. In the header

### ISSUE THREAD

**Issue by georgerhewitt** [uswds/uswds#4184]
### Describe the bug
Mouse rollover causes Uncaught TypeError.  Nav header dropdown will through the error when mousing over the dropdown and mousing out

### Steps to reproduce the bug
1. Go to 'https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.11.2/components/preview/header--basic-mega.html'
2. Mouse over the dropdown several times to trigger the error
4. See Uncaught TypeError:

### Expected behavior
That no error will occur when mousing over the dropdown nav

### Screenshots
Add screenshots to help provide context, if applicable.

### System setup
- **USWDS version: 2.11.2**
- **Device: PC**
- **Operating system: Windows 10 **
- **Browser and version: Firefox Version 87.0**

### Additional context
Add any other context about the problem.

**Comment by mahoneycm** [comment]
Confirmed problem appears to be coming from Receptor

**Comment by aduth** [comment]
I was able to reproduce this, but only in Firefox, and only on Windows.

![Screen Shot 2021-07-01 at 12 27 19 PM](https://user-images.githubusercontent.com/1779930/124159427-27dabd00-da69-11eb-8d65-a1f4d4213bf2.png)

Like @mahoneycm discovered, it does seem to stem from `receptor`, specifically this line:

https://github.com/shawnbot/receptor/blob/de712fd134c5fb1f9c48671579245d58d3296bcd/src/delegate.js#L6

The problem is that it's assumed to exist, and apparently assumed to be an [`Element`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest). As seen in the above screenshot, it can also be a [`Text` node](https://developer.mozilla.org/en-US/docs/Web/API/Text), which doesn't have `closest`. [According to the spec](https://dom.spec.whatwg.org/#event), it could also be `null`, which is also not handled.

An upstream pull request could be in order. Or: Also seen in the screenshot above, this is happening in response to trying to handle `mousemove` events. I assume this is for the ComboBox component ([source](https://github.com/uswds/uswds/blob/d0aed04a10b52b2250085d3490502a6b743fc4ef/src/js/components/combo-box.js#L776)). `mousemove` is an incredibly noisy event that's likely to have a performance impact, especially problematic considering the component may not be present at all. It may be possible to indirectly fix this by changing to a different event (e.g. `mouseover`, `mouseout`) or avoiding event delegation altogether.
