### ISSUE TITLE
Text not included in an ARIA landmark

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4267]
Siteimprove: https://drive.google.com/file/d/1PnvCp1vXSM_DXur2Hzkl_1WcE6Pz5t50/view?usp=sharing

- [x] DW to re-check this.

**Comment by mejiaj** [comment]
✔ Next report nav is in a landmark — fixed in USWDS-Site commit [005beea](https://github.com/uswds/uswds-site/commit/005beeaa9e790ea428ad91fd8c00ce1bc8c93a2b).
❌ Skipnav link in landmark ⚠

⚠ I still see ARIA landmark issue with the Skip link in Siteimprove's a11y checker browser extension. This seems like a false positive. For example, neither [GovUK](https://www.gov.uk/), [USA.gov](https://www.usa.gov/), or even [W3.org's docs](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html) have the skip link in a landmark.

**Comment by thisisdano** [comment]
We will not move the skipnav at this time.
