### ISSUE TITLE
External Links icon not rendering properly in Safari

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4434]
The external link icon is not rendering correctly in Safari

**Comment by aduth** [comment]
@mejiaj Apologies if there's been some debugging on this already, but I figured to drop some notes here, since I see you're assigned, but I suspect this could be a regression of (or at least started as of) my changes in #4297:

This is what I see in Safari on the [Link documentation page](https://designsystem.digital.gov/components/link/):

![image](https://user-images.githubusercontent.com/1779930/146996104-6d1984e7-d24c-4c56-9c38-9951726f35cf.png)

I think the issue is in-part because the `:after` pseudo-element takes the full height of the line by default:

![image](https://user-images.githubusercontent.com/1779930/146996326-d9094a13-d4b9-4a21-b183-ae54774f3f10.png)

And with the changes in #4297, we assign background color to the text color:

![image](https://user-images.githubusercontent.com/1779930/146996608-944ffd44-6714-403f-af23-e18f22f24946.png)

But the background sprite icon itself is only 1.75ex:

![image](https://user-images.githubusercontent.com/1779930/146996369-9e199475-659e-430a-b0ce-431fe15acc15.png)

Setting the width and height explicitly seems to help:

![image](https://user-images.githubusercontent.com/1779930/146996425-2e1d2bf7-370a-4120-8f71-b71916f9dcd0.png)

![image](https://user-images.githubusercontent.com/1779930/146996440-a80d97c0-5c5c-4a11-82cb-67c2277f19d2.png)

But it does have a small impact on spacing around it.

Also, as far as where to introduce this "fix", I'm not sure if this is an issue specific to the external link, or if it makes sense to incorporate handling for this in the `add-color-icon` mixin.

**Comment by mejiaj** [comment]
@aduth hey, thanks for looking into this. I was out last week, but did some brief debugging. One of the possible fixes I was looking at was setting dimensions and `background-size: cover`.
