### ISSUE TITLE
USWDS - Bug: Links styled as buttons break in forms

### ISSUE THREAD

**Issue by scottkellum** [uswds/uswds#5066]
### Describe the bug

This commit seems to break button styling in forms: https://github.com/uswds/uswds/pull/2921/commits/8b57c7b628acf537d8fb2bd91ca68eb8467aa5aa

Button and link styling seem to be working fine without this line. I’m not sure what bug it was meant to solve in the first place but maybe it doesn’t need to be there anymore? If it does need to be there, increasing the specificity of buttons will work by doubling the [class on _usa-button.scss](https://github.com/uswds/uswds/blob/develop/packages/usa-button/src/styles/_usa-button.scss#L9) to `.usa-button.usa-button`. This is, of coarse, not very elegant. This is a specificity bug though.

### Steps to reproduce the bug

Use the following code on a USWDS page:

```html
<form class="usa-form">
	<a class="usa-button" href="#">This button text will be invisible</a>
	<input class="usa-button" type="submit" value="This text is visible" />
</form>
```

### Expected Behavior

The text in the button should be visible

### Related code

```html
<form class="usa-form">
	<a class="usa-button" href="#test">This button text will be invisible</a>
	<input class="usa-button" type="submit" value="This text is visible" />
</form>
```

### Screenshots

![Screenshot 2022-12-09 at 4 16 06 PM](https://user-images.githubusercontent.com/377189/206815897-7166b12d-fb01-4dab-9d21-152c6aeaef2b.png)

### System setup

- USWDS 3.3.0
- Mac Mini M1
- Mac OS 13.0.1
- Chromium based browser (Arc 0.80.0)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
I am able to replicate the bug. The `typeset-link` mixin is important because it overrides clicked links as well. For example, in this screenshot the `Forgot password?` link turns purple without `typeset-link`

![Image](https://user-images.githubusercontent.com/25211650/213534897-8c3eb700-2cff-49e3-9be3-b281f05c5a88.png)

@mejiaj  It looks like we could try out the `:not()` selector to target anchor tags with the `usa-button` class. We've used it before and it has pretty good usability on [CanIUse](https://caniuse.com/mdn-css_selectors_not#:~:text=CSS%20selector%3A%20Negation%20pseudo%2Dclass%20selector%20(%3Anot()))

```scss
  a:not(.usa-button) {
    @include typeset-link;
  }
```

Result:


![Image](https://user-images.githubusercontent.com/25211650/213535979-d84c4ac4-eebb-47df-ac0e-c3b917078bce.png)
