### ISSUE TITLE
USWDS - Disabled styles: Perform landscape analysis of existing disabled styles solutions

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5117]
In this task, we should research and catalog the solutions for disabled styles that already exist in the market. We should:
    - Document default styles for disabled elements in relevant browsers
    - Compare how other design systems style disabled elements
    - Discover what other industry leaders recommend for disabled styles

**Comment by mahoneycm** [comment]
I collected examples of browser styles, other design systems, and various writeups and compiled it into this [Arc Easel](https://arc.net/e/DC914884-90DA-4C1C-B617-3600B1980663)

# Default Browser Styles

![image](https://user-images.githubusercontent.com/25211650/219788246-fa343e50-ff58-45cd-8490-993ea5a69b4a.png)

### Chrome
- Adjusts opacity on form inputs & uswds forms

### Firefox
- Light opacity shift on default inputs
- No effect on uswds styles

### Safari
- Light opacity shift on default inputs
- No effect on uswds styles

### Edge (macOS)
- Adjusts opacity on form inputs & uswds forms

## Various inputs w/ Chrome disabled styles

<img src="https://user-images.githubusercontent.com/25211650/219788934-7a90542b-97b7-48d8-bef4-7a9764401313.png" align="right" width="50%"/>

While Chromium browsers offer some disabled styles, they leave room for improvement

	●	Changes are minor
	●	Text fails color contrast minimums
	●	No cursor style change

<br clear="right"/>

---

# Other Design System Solutions

## [UK.gov](https://uk.gov/) Design System

### Button

<img src="https://user-images.githubusercontent.com/25211650/219790373-e1d7aaa2-fead-4209-a567-0e8e755a1a1a.png" align="right" width="50%"/>


- Uses class to set the opacity

```scss
.govuk-button--disabled, 
.govuk-button[disabled=disabled], 
.govuk-button[disabled] {
    opacity: .5;
}
```


<br clear="right"/>

### Checkboxes / Radio
<img src="https://user-images.githubusercontent.com/25211650/219791998-ee06fe95-7f27-4fc2-b3b5-d9ef913ace05.png" align="right" width="50%"/>

- Uses attr to set cursor to default

```scss
.govuk-checkboxes__input:disabled, 
.govuk-checkboxes__input:disabled+.govuk-checkboxes__label {
    cursor: default;
}
```

<br>

- Uses attr selector with combinator to set label and checkbox (set by pseudo-element) opacity


```scss
.govuk-checkboxes__input:disabled+.govuk-checkboxes__label, 
.govuk-checkboxes__input:disabled~.govuk-hint {
    opacity: .5;
}
```

<br clear="right"/>


---

## [VA.gov](https://va.gov/) Design System

VA.gov Design System has a great guidance section on not disabling buttons.

It explains why it is generally a bad idea, gives alternative solutions, and even includes an example of when it might be valid to disable a button [^1]

> **Accessibility considerations for all form elements**
>
>**Do not disable buttons**
>Normally, with regular form controls, it is best to fully remove anything the user can’t interact with or which serves no purpose. However, disabling a “button” to act as a guide to the level of form completion (i.e. you are not able to proceed to the next step until the form contains enough data) is a common anti-pattern.
>**Disabled buttons don’t explain what’s wrong**
>
>When buttons are inactive, some users– particularly those with cognitive disabilities- may not know how to activate them. Disabled buttons don’t explain what’s wrong. They communicate that something is off, but very often that is not enough information. As a result, users are left wondering what’s actually missing, and consequently are locked out entirely. For example, if someone were to type in a short acronym like “VA” to search and the button doesn’t become accessible, they may think the search field is broken.
>
> In addition, disabled buttons can be unintentionally read out and accessed by mobile screen readers using touch controls.
> **What to do instead**
> While it is technically possible, we strongly discourage disabling buttons. Here are recommendations on how to handle specific interactions:
> - **Lack of required fields**. When a user attempts to submit a form without entering all required form fields:
>     - Announce the error and shift focus to the first unfilled required form field.
>    - Properly indicate required form elements (the right thing will happen for you when you use the required property on form fields in the Design System).
>
> - **No longer valid options**. If certain options in a form are no longer valid then there are two options:
          1. Replace the form elements that can no longer be changed with text representing the current value instead of the current value within a disabled input.
          2. Hide the form elements that are no longer valid.
>
>**Is it ever valid to disable a button?**
> Post-form submission or post-action it can be appropriate to disable the submit or action button as the system is in-between states and loading or taking action. This behavior is often seen on buttons that make a purchase or reservation to prevent the user from accidentally triggering the action multiple times.

[^1]: https://design.va.gov/components/form/#accessibility-considerations-for-all-form-elements

### Button

<img src="https://user-images.githubusercontent.com/25211650/219794427-7556e7cd-c021-40e3-bdc4-9fa3df5b1628.png" align="right" width="45%"/>


- Only form element with custom disabled styles
- Uses attr on <va-button> element to set cursor to disabled

<br clear="right"/>

```scss
<va-button disabled text="Edit" class="hydrated">
   #shadow-root (open)
        <button aria-disabled="true" type="button" part="button">Edit</button>
</va-button>
```

```scss
:host([disabled]:not([disabled="false"])) {
    cursor: not-allowed;
}
```

- Combines the above with a button selector to set visual styles

```scss
:host([disabled]:not([disabled="false"])) button {
    background-color: var(--color-gray-lighter);
    box-shadow: none;
    color: var(---color-white);
    pointer-events: none;
}
```

_*Note: They use :not([disabled="false"]) as a on <va-button>. I wanted to note that setting disabled=“false” to button elements in default circumstances will still cause browser agent styles to enable disabled styles. 

It also uses `pointer-events: none` which is not recommended because users can still tab to the element and use enter to activate it [^2]_

[^2]: https://css-tricks.com/making-disabled-buttons-more-inclusive/#aa-2-do-not-use-pointer-events-to-prevent-the-click




<br clear="left"/>

## Bootstrap

### Disabled forms

- Custom styles on disabled attribute
- Forms take `.form-input` class and the selector combines that with the disabled attr.

![image](https://user-images.githubusercontent.com/25211650/220373107-1f1fec34-e7f2-43ad-8495-8fc396585718.png)

_*Note about achors_
![image](https://user-images.githubusercontent.com/25211650/220372768-5cadbd5e-35cb-4bdb-ab2a-a5d27ed03f6d.png)

### Radio and Checkboxes

- Styles set via attribute
- Input styled via general sibling combinator

```Scss
.form-check-input:disabled~.form-check-label {
    color: #6c757d;
}
```

![image](https://user-images.githubusercontent.com/25211650/220373485-5ec28f5a-1e43-48aa-8820-e5dad1634c1e.png)
![image](https://user-images.githubusercontent.com/25211650/220373501-d916c3b7-743b-458b-81e4-fa1ade70ce9b.png)

### Buttons

- Set by attribute
- Includes guidance on anchors styled as buttons
- Changes to a defined color
- No mouse hover effects

![image](https://user-images.githubusercontent.com/25211650/220373705-35e4646b-0aa7-45a5-98b8-8e95823161bc.png)


## Other recommendations and write-ups

### [CSS Tricks - Making Disabled Buttons More Inclusive](https://css-tricks.com/making-disabled-buttons-more-inclusive/)

Great article outlining the shortcomings of the disabled attribute and instructs how aria-disabled and a little bit of JS can deliver a better user experience to screen-reader users

![image](https://user-images.githubusercontent.com/25211650/220374099-02c058ee-2b40-41a4-a9f2-f95e31b5b5fd.png)
![image](https://user-images.githubusercontent.com/25211650/220374112-fbeac3a4-1ba8-4a13-87b7-b76a58ab5ff9.png)

It goes further to encourage developers to allow users to click the button, and instead show an error message

![image](https://user-images.githubusercontent.com/25211650/220374222-4477abb9-7e1f-4535-bac2-0e79b7acb19f.png)

### [HTML.form.guide](https://html.form.guide/best-practices/form-validations-definitive-guide/#:~:text=Blocking%20the%20user%20is%20a%20bad%20practice)

Short & sweet explanation on why blocking the user is bad practice. It instructs to instead allow them to click the button and then show a message on why they can’t proceed.

![image](https://user-images.githubusercontent.com/25211650/220376349-437d1d86-6f97-4c9d-ac22-a6c12da857fe.png)

**Comment by mahoneycm** [comment]
Added my findings above to the USWDS Research Drive 👍

**Comment by jaclinec** [comment]
I've wrapped up the [disabled styles literature review ](https://docs.google.com/document/d/1D0zOwYq612ok5mqgzZeZ943H1HLG0z76JqorQdq5cKw/edit?usp=sharing)and much of my findings correlate with Charlie's. Here is a summary:


**Summary of findings**
Overwhelming evidence in the literature says to not use disabled states at all. It’s bad UX and bad for accessibility. Instead, allow users to interact but show helpful error messages/feedback.

**Summary of reasons to NOT use disabled styles:**

- They fool users into clicking
- They are hard to see
- They don’t give feedback
- They give design teams a reason to rush through error handling
- They make users think
- They create a barrier to people with disabilities

**What to do instead:**

- Enable the given UI element. Then, upon user interaction, you can provide feedback.
- add a contextual helper text
- use a tooltip
- validate user input on submit
- Use inline validation. [Inline validation](https://medium.com/wdstack/inline-validation-in-forms-designing-the-experience-123fb34088ce#.n27h3lxl7) can prevent users from seeing error messages in the first place. By validating user input on the fly you can reassure them that their input is correct. Of course, inline validation won’t guarantee that the user input is 100% correct, but it’s possible to minimize the chance of seeing error message after the user clicks Submit.
- Show well-designed error message on button click. A good error message helps users understand what causes the problem and guides them to find a solution.

**Possible reasons to use disabled styles:**

- Loading/Processing & error prevention: 

a process is loading, e.g. the user has already initiated the given action (ex: hit the ‘Submit’ button and it is loading..you don’t want the user to hit submit again) 
it might help users avoid unintentional user actions/error prevention, e.g. paying multiple times 
another example: asking user to submit a file but not allowing submission until file is fully uploaded -[example source](https://www.quora.com/When-is-it-preferable-to-hide-a-disabled-button-in-an-interface-instead-of-showing-it-in-a-disabled-state) 

- Gating and Discoverability: 

You want the user to know that the control exists, but that it is disabled. 
Example: Controlling access to certain parts (e.g. an account, a subscription or a premium membership required) 
Example: showing different size clothing options but the sold out options are disabled

- Upcoming: Something yet to be released (not yet available)

Example: an item is not available in a web shop or a day is not available in an appointment scheduling tool

- Input issue: User has not yet filled in any form inputs

When all fields/inputs are empty in a form (i.e. the user has just arrived and not interacted with the form at all/ filled anything out yet). Enable the CTA as soon as the user provides any data, even if it isn’t complete/valid.

**If you are going to use disabled states, follow best practices:**

- Instead of using the native disabled attribute, use aria-disabled so it announces correctly to screen readers that it is unavailable, but you will still need to prevent the click programmatically, using JavaScript. ([css-tricks.com](https://css-tricks.com/making-disabled-buttons-more-inclusive/))
- Do some css magic and make it look a bit gray (but with sufficient contrasts). And then turn it green or blue when everything is filled in correctly. But keep the button enabled in the code at all times and put focus on an error message if it’s clicked and there’s something wrong. ([axess lab](https://axesslab.com/disabled-buttons-suck/))
- Provide a hover bubble/tooltip/[detail disclosure buttons](https://developer.apple.com/design/human-interface-guidelines/ios/controls/buttons/) or other feedback message explaining the criteria for use and informing users what actions they can take to enable them.

**Choose to hide elements rather than disable when:**

- If the user is not authorized to use the control which means it is never available to the user.
- If it is a control that is only active in very rare situations. Don’t show the user a button that can’t be used or enabled to be used.
- If a page has a lot of disabled functionality. For instance, a whole extra block of form inputs.

**References list**
[W3C](https://design-system.w3.org/styles/buttons.html) Buttons page
[WCAG Understanding Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)
[Axess Lab - Disabled buttons suck](https://axesslab.com/disabled-buttons-suck/)
[The disabled state in UI design](https://uxknowledgebase.com/the-disabled-state-in-ui-design-8c091d72868)
[Hidden vs. disabled states](https://uxpsychology.substack.com/p/hidden-vs-disabled-states) 
[Disabled buttons in user interface](https://uxplanet.org/disabled-buttons-in-user-interface-4dafda3e6fe7)
[Making disabled buttons more inclusive](https://css-tricks.com/making-disabled-buttons-more-inclusive/)

**Comment by jaclinec** [comment]
I believe next step is to discuss as a team the "possible reasons to use disabled styles" as outlined above, and what we might want to test there. For instance, I'm curious how the user experience differs between 2 options: disabling a button with aria-disabled + JS versus just keeping it enabled and showing feedback in some way. There are a couple different scenarios we could test there.

**Comment by jaclinec** [comment]
@amyleadem @mejiaj  Please review and add any comments or thoughts you have to the [literature review doc ](https://docs.google.com/document/d/1D0zOwYq612ok5mqgzZeZ943H1HLG0z76JqorQdq5cKw/edit?usp=sharing)(first 2 pages are where summary of findings are). Once you've had a chance to look at it, we can mark this as fed final review. Thanks!

**Comment by jaclinec** [comment]
@thisisdano Today I reviewed and updated the literature review to include another source, to clean up some of the recommendations for 'what to do instead' and 'best practices,' and add more links to more easily reference material in the content.

The literature review was done with a focus on the internal USWDS team being the audience. More work will be needed to bring this to a publishable state for the public.

Next steps are to identify where on the site we want to edit or add guidance for disabled styles ([#2144](https://github.com/uswds/uswds-site/issues/2144)). Then, write guidance and publish to the site. ([#2108](https://github.com/uswds/uswds-site/issues/2108))

**Comment by thisisdano** [comment]
Thanks all!
