### ISSUE TITLE
USWDS - Disabled styles: Draft communications plan for sharing progress

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5196]
Communication pillars: 

- Problem to solve: inconsistent styling across browsers
- Guidance: mention that from a UX perspective it’s tricky to get it right
- UX: There shouldn’t be a disabled element. If it doesn’t have a function don’t put it on the page
- Accessibility: certain disabled components would fail color contrast and make noncompliant with wcag standards
- (there’s an argument out there that if it’s disabled it doesn’t have to pass wcag, but we disagree)
- Put in the extra work to make uniform experience even if not required

Comms action items

- [x] Put in Monthly call editorial calendar to do a deep dive into this once it’s published
- [ ] Do a deep dive in the newsletter
- [ ] Open up a github discussion

**Comment by bonnieAcameron** [comment]
Notes from the meeting: Jun 28, 2023 | [Comms for Disabled States]
Attendees: [Bonnie Cameron](mailto:bonnie.cameron@bixal.com) [Bonnie Cameron - QQE-C](mailto:bonnie.cameron@gsa.gov) [Charles Mahoney - QQ-C](mailto:charles.mahoney@gsa.gov) [charlie.mahoney@bixal.com](mailto:charlie.mahoney@bixal.com)  [sarah.schroeder@bixal.com](mailto:sarah.schroeder@bixal.com) [Sarah Schroeder - QXA-C](mailto:sarah.schroeder@gsa.gov)

Notes
Previously disabled styles was there but inconsistent (button, checkbox, file input)
Charlie created new ones: text input, range slider, and some of the other components that didn’t have USWDS defined styles, relied on browser styles 
Immediate need for devs & designers: wise to offer disabled guidance for form elements. This might be something that is reusable markdown blocks where you say “include disabled style guidance” one source of truth
We’re making an effort to keep disabled styles consistent across browsers which is why we’re making a uswds defined style 
Offer a way to disable them 
Might be a good idea somewhere within documentation/guidance design principles and patterns
https://github.com/uswds/uswds/issues/5117
[Disabled styles literature review](https://docs.google.com/document/d/1D0zOwYq612ok5mqgzZeZ943H1HLG0z76JqorQdq5cKw/edit)
Va design system: accessibility considerations for all form elements, then they say “don’t do it!)
Riff off of VA documentation for our site on disabled styles

Comms pillars: 
Problem to solve: inconsistent styling across browsers
Guidance: mention that from a UX perspective it’s tricky to get it right
UX: There shouldn’t be a disabled element. If it doesn’t have a function don’t put it on the page
Accessibility: certain disabled components would fail color contrast and make noncompliant with wcag standards
(there’s an argument out there that if it’s disabled it doesn’t have to pass wcag, but we disagree)
Put in the exta work to make uniform experience even if not required

Comms action items
Put in Monthly call editorial calendar to do a deep dive into this once it’s published
Do a deep dive in the newsletter
Open up a github discussion
