### ISSUE TITLE
Buttons are rendering with empty "type"

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5246]
Buttons are compiling with `type=""`, they should be using `type="button"`. This is affecting our documentation. For example [Buttons](https://designsystem.digital.gov/components/button/)

![image](https://user-images.githubusercontent.com/3385219/233382982-ab17edbf-43d2-44ae-975d-fc8de13a643c.png)

**Comment by mahoneycm** [comment]
It looks like this is happening because the `type` attribute isn't being defined in the components `json` file. On storybook, we're defining the attribute as a control with a default value, but it doesn't get compiled with webpack.

I've created a solution on #5247 which sets the default `button.json` `type="button"`. Everything seems to be working appropriately! Let me know if you see any implications of this solution that I may be missing
