### ISSUE TITLE
USWDS - Feature: Move usa-input--[width] classes to the usa-input module

### ISSUE THREAD

**Issue by jamigibbs** [uswds/uswds#5312]
### Is your feature request related to a problem? Please describe.

We have a need for applying the `.usa-input--[width]` class to a standalone web component. I had hoped that those classes were included with the `usa-input` module but they are instead in `usa-form` nested under the `.usa-form` class.

https://github.com/uswds/uswds/blob/develop/packages/usa-form/src/styles/_usa-form.scss

Being an individual component, I did not think it appropriate to wrap it with `.usa-form` just so that we could access the width classes. It seems like `.usa-form` is intended to be used on a wrapping element around an entire form.

### Describe the solution you'd like

It would be ideal in our use case to have the `usa-input--[width]` available as part of the `usa-input` module. As it is now, we would need to copy those classes into our component library as a mixin which isn't ideal because we'd like to continue to pull them directly from the USWDS library instead.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by aduth** [comment]
We ran into this issue recently in our project, since we don't include the `usa-form` package, but expected to be able to use width variants `.usa-input--[width]` since we _do_ include the `usa-input` package.

This feels like a bug to me rather than a feature request, since I think it's reasonable to expect that including the package documented for a component (`usa-input` in the case of [Text Input](https://designsystem.digital.gov/components/text-input/)) would make available all of the usage options documented for that component.
