### ISSUE TITLE
USWDS - Bug: ARIA attribute unsupported or prohibited on Modals

### ISSUE THREAD

**Issue by nloand** [uswds/uswds#5456]
### Describe the bug

Using the Modal component code, I am getting the following accessibility errors via SiteImprove:

An ARIA attribute has been specified that is either not supported or is prohibited, on this type of element.
- `aria-labelledby` on `div`

### Steps to reproduce the bug

In the component code the "aria-labelledby" is being flagged as not supported or is prohibited, on this type of element.
```
<div
    class="usa-modal"
    id="example-modal-1"
    aria-labelledby="modal-1-heading"
    aria-describedby="modal-1-description"
  >
    <div class="usa-modal__content">
      <div class="usa-modal__main">
        <h2 class="usa-modal__heading" id="modal-1-heading">
          Are you sure you want to continue?
        </h2>
```

### Expected Behavior

Expected to not flag SiteImprove

### System setup

- USWDS 2.13

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mahoneycm** [comment]
Hello @nloand,

Is the modal properly initializing on your page before the Siteimprove test runs?

The code snippet you included is the pre-initialization markup. During JS initialization USWDS takes some of these values and restructures the Modal markup. Part of this restructuring, moves the `aria-labelledby` attribute to the newly generated modal wrapper, which also receives `role="dialog"`.

We have not been successful in recreating this error, and I believe that is because of the dialog role.

From a Harvard University digital accessibility article on Accessible modal dialogs[^1]:

> Note the `dialog` role, which tells assistive technologies that the element is a dialog. The `aria-labelledby` and `aria-describedby` attributes are “relationship” attributes that connect the dialog to its title and description explicitly. So when focus is moved to the dialog or inside it, the text within those two elements will be read in succession.
> 

[^1]: [https://accessibility.huit.harvard.edu/technique-accessible-modal-dialogs#:~:text=Note the,interact with it](https://accessibility.huit.harvard.edu/technique-accessible-modal-dialogs#:~:text=Note%20the,interact%20with%20it).

Are you able to confirm that the modal is initializing properly on your page before the SiteImprove test runs?

**Comment by mahoneycm** [comment]
Hey there @nloand just following up. 

Are you able to confirm that the modal has initialized before the SiteImprove test ran?

**Comment by nloand** [comment]
Thanks for following up! The SiteImprove team accepted the flag as being a false positive, so it’s not an “issue” on our site any longer.

**Comment by mahoneycm** [comment]
@nloand Thanks for the update! I'm going to close the ticket since it's a non-issue 👍
