### ISSUE TITLE
Add styles for responsive tables

### ISSUE THREAD

**Issue by line47** [uswds/uswds#896]
**Description**
Add classes to be used for responsive tables so that tabular data is formatted for smaller screens
At certain breakpoints the table will be transformed into a reflow style stacking the rows.
This uses data-title attributes to place header text for each item in a row

**Additional Info**
Live example on codepen: http://codepen.io/line47/pen/QjRjQa

**Comment by maya** [comment]
@line47 thanks so much for bringing this up AND the working code. There are several different possibilities for dealing with tables on smaller screens (from the simple horizontal scroll to the more robust [Tablesaw](https://www.filamentgroup.com/lab/tablesaw.html) by Filament Group) and we'll likely investigate this more as we start the next phase of work. Definetly think your idea is really good and will share with the team.

Stay tuned!

**Comment by line47** [comment]
Thanks @maya! I've got some additional CSS that can be used for a more card type layout at mobile.

The trouble I have with horizontal scrolling is how does the user know that the table can be scrolled horizontally. All responsive tables that use horizontal scrolling that I've seen have no indicator to the user that there is more content to the right.

**Comment by Drakenhart** [comment]
@maya For some users who are non-visual, this may not be as big an issue. However, @line47 is right, few of them are not obvious that you can scroll sideways.

Scroll sideways in general on websites as a whole is something that we've tried to move away from over the years, as it is not a natural motion for someone using the web from a desktop (or at least hasn't been since before the inception of tablets that can surf desktop-sized sites).

The same could also be said of someone using a phone. Mobile users (including tablet) do not often scroll or swipe sideways unless it is a designated sideways swipe feature. (ie menu options)

The question then begs if you break up a table in a menu-style side swipe, how does that effect non-visual users?

A second question too, is the use of tables that are already stacked? Will tables be forced to be one style only (horizontal)? Or can we design them to be stacked as well? How would they be made responsive?

**Comment by wslack** [comment]
The only idea I would add after noticing this on another site:

It might be possible (maybe?) to use something like the bubble effect on the Mac dock, which would expand text in middle of table but still showing that there's more context not displayed full size.

**Comment by maya** [comment]
This is not on the current product roadmap, closing for now.

**Comment by thisisdano** [comment]
We're getting back into responsive tables, and I'm interested in this solution. On the plus side, it seems pretty bulletproof. You lose some of the context of a column of data, and get a lot of redundancy, but I'm inclined to think it's worth it in many cases.

I'm going to try and implement it on the v2 website and then think about if and how to incorporate it into our standard component.

**Comment by thisisdano** [comment]
After three years...

**Comment by thisisdano** [comment]
@line47 in the intervening time, have you come to any different conclusions about a good solution?

**Comment by thisisdano** [comment]
Other js-based options:
https://datatables.net/
http://filamentgroup.github.io/tablesaw/demo/swipe.html

**Comment by line47** [comment]
@thisisdano my thinking at the time was building something that worked without JS and was easy to implement. I'd love to find a way to reduce the redundancy as well.

**Comment by sknep** [comment]
@thisisdano This seems covered in the latest update to tables.

**Comment by thisisdano** [comment]
Yup!
