### ISSUE TITLE
Grid system section needs more depth

### ISSUE THREAD

**Issue by nkkl** [uswds/uswds#901]
**Description**
The section on [how to use the grid system](https://playbook.cio.gov/designstandards/grids/) provides insufficient detail on how to design with the provided grid system. Explaining it better detail will allow designers (especially those with less experience) to work within the provided standards and enable teams without designers to make better design decisions.

**Ask**
Surface specific details of the grid system (ex. minimum of 30px gutters, minimum column widths, media query breakpoints, etc.).

**To Do**
- [x] Explain media query breakpoints, especially as applies to switching devices
- [x] Explain gutters and column min/max widths
- [ ] Explain how/if fonts responsively resize and how sizing is handled on large screens (ex. if a 12-column layout leads to columns that are significantly wider than 75em)
- [ ] Consider adding a section on mobile devices that goes into depth on how to design touch-friendly websites

**Comment by Drakenhart** [comment]
I support this improvement.

Working on another government project I had to dig through the code to find this sort of information and used a significant amount of time trying to find this so I could set up a Photoshop document for my visual design work. (I use both Illustrator and Photoshop to work up visuals.)

- [ ] Note what the base font size is (please).
- [ ] Make it more obvious that some of this information is in the accordions (font size, weight, etc are all hidden and it's not obvious where this information is easily located).
- [ ] Also when clarifying responsive design, please specify how this handles higher resolution devices (ex. ipad, iphones) that might otherwise display the desktop layout on a phone. 

:+1:

**Comment by mebates** [comment]
Also looking for some help on the fixed gutter width! More detail in the grid section would be great. CFPB's is a bit more clear: https://cfpb.github.io/design-manual/ui-toolkit/grid-and-layout.html

**Comment by maya** [comment]
@nkkl we've addressed this in our new grid system in https://github.com/uswds/uswds-site/pull/580 which will be released in version 2.0. Could you [take a look](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-grids/utilities/layout-grid/) and see if it meets your needs?

**Comment by maya** [comment]
Good things come to those who wait :)
